"""Generate a navigable overview of an exploded workspace.

Once a codebase is on disk, the thing missing is a way in. The IDE gives you a
tree to click; a directory of exports gives you nothing until you already know
what you are looking for. This writes that way in as Markdown, with relative
links so it works in an editor, on GitHub, and in a pull request.

It is a derived view: regenerate it after re-exploding rather than editing it.
Nothing reads it back, so it cannot affect fidelity.
"""

from __future__ import annotations

import io
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from . import usage as usage_mod
from . import xref as xref_mod
from .explode import PROPERTIES, read_properties

INDEX = "INDEX.md"

# Tables whose rows are objects worth listing, and what to call them.
OBJECT_TABLES = {
    "UFORM": "Components",
    "USOURCE": "Library ProcScript",
    "UCTABLE": "Model entities",
    "UCGROUP": "Model entities",
    "UCFIELD": "Model fields",
    "UXGROUP": "Entities used by components",
    "UXFIELD": "Fields used by components",
}
# Listed in their own right; the rest are reached through their parent.
HEADLINE_TABLES = ("UFORM", "USOURCE")


@dataclass
class Obj:
    export: str
    table: str
    name: str
    directory: str            # workspace-relative
    properties: dict = field(default_factory=dict)
    code: list = field(default_factory=list)   # (filename, line count)

    @property
    def description(self) -> str:
        return self.properties.get("UDESCR", "")

    @property
    def lines(self) -> int:
        return sum(n for _, n in self.code)


def scan(root: Path) -> list:
    objects: list = []
    for properties_file in sorted(root.rglob(PROPERTIES)):
        directory = properties_file.parent
        parts = directory.relative_to(root).as_posix().split("/")
        if len(parts) < 2:
            continue
        table = parts[-2]
        export = "/".join(parts[:-2]) or "(root)"
        code = []
        for path in sorted(directory.glob("*.proc")):
            text = path.read_text(encoding="utf-8", errors="replace", newline="")
            code.append((path.name, text.count("\n") + 1 if text else 0))
        objects.append(Obj(
            export=export,
            table=table,
            name=parts[-1],
            directory=directory.relative_to(root).as_posix(),
            properties=read_properties(properties_file),
            code=code,
        ))
    return objects


def link(text: str, target: str) -> str:
    return "[%s](%s)" % (text, target)


def render(root: Path) -> str:
    objects = scan(root)
    data = usage_mod.build(root)
    code = xref_mod.build(root)

    exports = sorted({o.export for o in objects})
    by_table = defaultdict(list)
    for obj in objects:
        by_table[obj.table].append(obj)

    out = io.StringIO()
    out.write("# Workspace index\n\n")
    out.write("Generated by `unifold index`. Regenerate after re-exploding; "
              "this file is a derived\nview and nothing reads it back.\n\n")

    out.write("| | |\n|---|---|\n")
    out.write("| Exports | %d |\n" % len(exports))
    out.write("| Objects | %d |\n" % len(objects))
    out.write("| ProcScript files | %d |\n" % code.files)
    out.write("| ProcScript lines | %d |\n" % sum(o.lines for o in objects))
    out.write("| Definitions | %d |\n" % len(code.definitions))
    out.write("| Calls | %d |\n" % len(code.references))
    out.write("\n")

    for table in HEADLINE_TABLES:
        entries = sorted(by_table.get(table, []), key=lambda o: (o.name, o.export))
        if not entries:
            continue
        out.write("## %s (`%s`) - %d\n\n" % (
            OBJECT_TABLES.get(table, table), table, len(entries)))
        out.write("| Name | Export | Code | Lines | Description |\n")
        out.write("|---|---|---:|---:|---|\n")
        for obj in entries:
            files = ", ".join(
                link(name, "%s/%s" % (obj.directory, name)) for name, _ in obj.code
            ) or "-"
            out.write("| %s | %s | %s | %s | %s |\n" % (
                link(obj.name, obj.directory), obj.export, files,
                obj.lines or "-", obj.description or "",
            ))
        out.write("\n")

    entities = sorted({u.key for u in data.usages if u.kind == "entity"})
    if entities:
        out.write("## Data model - %d entit%s in use\n\n"
                  % (len(entities), "y" if len(entities) == 1 else "ies"))
        out.write("| Entity | Used by | Fields in use |\n|---|---|---:|\n")
        for key in entities:
            users = sorted({u.component for u in data.usages
                            if u.kind == "entity" and u.key == key})
            entity = key.split(".")[-1]
            fields = {u.name for u in data.usages
                      if u.kind == "field" and u.entity == entity}
            out.write("| `%s` | %s | %d |\n"
                      % (key, ", ".join(users), len(fields)))
        out.write("\n")

    unresolved = code.unresolved()
    if unresolved:
        out.write("## External dependencies - %d\n\n" % len(unresolved))
        out.write("Called here but defined elsewhere; export those objects to "
                  "resolve them.\n\n")
        for ref in unresolved:
            via = ' via `"%s"`' % ref.service if ref.service else ""
            out.write("- `%s`%s\n" % (ref.name, via))
        out.write("\n")

    other = sorted(t for t in by_table if t not in HEADLINE_TABLES)
    if other:
        out.write("## Other tables\n\n| Table | Rows |\n|---|---:|\n")
        for table in other:
            out.write("| `%s` | %d |\n" % (table, len(by_table[table])))
        out.write("\n")

    out.write("---\n\nUse `unifold xref` for the questions this page only "
              "summarises:\n\n")
    out.write("```bash\n"
              "unifold xref . --symbol SOME_PROC     # who calls it\n"
              "unifold xref . --entity SOME_ENTITY   # who uses it\n"
              "unifold xref . --component SOME_NAME  # what it touches\n"
              "```\n")
    return out.getvalue()


def write(root: Path, out_file: Path = None) -> Path:
    target = out_file or (root / INDEX)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(root), encoding="utf-8", newline="")
    return target
