operation exec
; To run this operation, it must be declared ‘public web’. Otherwise, it results in a security error on the browser.
; The 'exec' operation is needed to access the static server page from a web client.
public web
; Your VARIABLES block here (optional)...

  ; Your pre-edit code here...

  webget   ; Load data submitted by web client
  if ($procerror == 0)
    ;webgen ; Generate a response based on the layout and component data
  else
	; Your error handling here...
  endif

  ; Your post-edit code here...

  ;   ;return 0    ; return >= 0 typically indicates a succesful execution
  ;return 0

	public web
#IF (<LC_DEBUG> == <GC_TRUE>)
#WARNING "Component is compilied with debug proc: DO NOT PATCH PAST DEVTEST"

call LT_TEST1
call LT_TEST2
call LT_TEST3
call LT_TEST4
call LT_TEST5
call LT_TEST6
call LT_TEST7
call LT_TEST8

entry LT_TEST1
	call LT_TEST_LF_PROCESS_OUTPUT("success=true[[uSEP]]message=[[uSEP]]sessionID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx[[uSEP]]language=ENG[[uSEP]]labellanguage=[[uSEP]]error=false[[uSEP]]errorId=Log in successful[[uSEP]]fullName=mobile[[uSEP]]role=[[uSEP]]contact=MOBILE[[uSEP]]RLS_WHERE=(RLS_GROUP IS NULL)[[uSEP]]userEmail=[[uSEP]]params=WOPARTSOPT=", <GC_FALSE>)
end ;LT_TEST1

;Indexed list
entry LT_TEST2
	call LT_TEST_LF_PROCESS_OUTPUT("ITEM1[[uSEP]]ITEM2[[uSEP]]ITEM3[[uSEP]]ITEM4[[uSEP]]ITEM5", <GC_TRUE>)
end ;LT_TEST2

;Associative list
entry LT_TEST3
	call LT_TEST_LF_PROCESS_OUTPUT("ITEM1=VALUE1[[uSEP]]ITEM2=VALUE2[[uSEP]]ITEM3=VALUE3[[uSEP]]ITEM4=VALUE4[[uSEP]]ITEM5=VALUE5", <GC_FALSE>)
end ;LT_TEST3

;Nested indexed list of indexed lists
entry LT_TEST4
	call LT_TEST_LF_PROCESS_OUTPUT("ITEM1[[uNOT]][[uSEP]]ITEM2[[uNOT]][[uSEP]]ITEM3[[uSEP]]ITEM4[[uNOT]][[uSEP]]ITEM5[[uNOT]][[uSEP]]ITEM6", <GC_TRUE>)
end ;LT_TEST4

;Nested associative list of indexed lists
entry LT_TEST5
	call LT_TEST_LF_PROCESS_OUTPUT("ARRAY1=ITEM1[[uNOT]][[uSEP]]ITEM2[[uNOT]][[uSEP]]ITEM3[[uSEP]]ARRAY2=ITEM4[[uNOT]][[uSEP]]ITEM5[[uNOT]][[uSEP]]ITEM6", <GC_FALSE>)
end ;LT_TEST5

;Nested indexed list of associative lists
entry LT_TEST6
	call LT_TEST_LF_PROCESS_OUTPUT("ITEM1=VALUE1[[uNOT]][[uSEP]]ITEM2=VALUE2[[uNOT]][[uSEP]]ITEM3=VALUE3[[uSEP]]ITEM4=VALUE4[[uNOT]][[uSEP]]ITEM5=VALUE5[[uNOT]][[uSEP]]ITEM6=VALUE6", <GC_TRUE>)
end ;LT_TEST6

;Nested associative list of associative lists of asscociative lists and indexed lists and indexed list
entry LT_TEST7
	call LT_TEST_LF_PROCESS_OUTPUT("OBJECT1=OBJECT2=ITEM1=VALUE1[[uNOT]][[uNOT]][[uSEP]]ITEM2=VALUE2[[uNOT]][[uNOT]][[uSEP]]ITEM3=VALUE3[[uNOT]][[uSEP]]OBJECT3=ITEM4=VALUE4[[uNOT]][[uNOT]][[uSEP]]ITEM5=VALUE5[[uNOT]][[uNOT]][[uSEP]]ITEM6=VALUE6[[uNOT]][[uSEP]]ARRAY1=VALUE7[[uNOT]][[uNOT]][[uSEP]]VALUE8[[uNOT]][[uNOT]][[uSEP]]VALUE9[[uSEP]]OBJECT4=ARRAY2=VALUE10[[uNOT]][[uNOT]][[uSEP]]VALUE11[[uNOT]][[uNOT]][[uSEP]]VALUE12[[uSEP]]ARRAY3=VALUE13[[uNOT]][[uSEP]]VALUE14[[uNOT]][[uSEP]]VALUE15", <GC_FALSE>)
end ;LT_TEST7

;Nested array of associative lists of asscociative lists and indexed lists and indexed list
entry LT_TEST8
	call LT_TEST_LF_PROCESS_OUTPUT("OBJECT2=ITEM1=VALUE1[[uNOT]][[uNOT]][[uSEP]]ITEM2=VALUE2[[uNOT]][[uNOT]][[uSEP]]ITEM3=VALUE3[[uNOT]][[uSEP]]OBJECT3=ITEM4=VALUE4[[uNOT]][[uNOT]][[uSEP]]ITEM5=VALUE5[[uNOT]][[uNOT]][[uSEP]]ITEM6=VALUE6[[uNOT]][[uSEP]]ARRAY1=VALUE7[[uNOT]][[uNOT]][[uSEP]]VALUE8[[uNOT]][[uNOT]][[uSEP]]VALUE9[[uSEP]]ARRAY2=VALUE10[[uNOT]][[uNOT]][[uSEP]]VALUE11[[uNOT]][[uNOT]][[uSEP]]VALUE12[[uSEP]]ARRAY3=VALUE13[[uNOT]][[uSEP]]VALUE14[[uNOT]][[uSEP]]VALUE15", <GC_TRUE>)
end ;LT_TEST8

entry LT_TEST_LF_PROCESS_OUTPUT
	params
		string  PV_LIST	: IN
		boolean PV_ARRAY	: IN
	endparams
	putmess $concat("LF_LIST_TO_STRUCT(%%"%%%", PV_LIST, "%%"%%%):%%^%%%", LF_PROCESS_OUTPUT(PV_LIST, PV_ARRAY))
end ;LT_TEST_LF_PROCESS_OUTPUT
#ENDIF



trigger erase
erase
if ($status <0)
   message $text(1763) ;error
   rollback
else
   if ($status = 1)
      message $text(1634) ;not allowed
   else
      message $text(1806) ;OK
      commit
   endif
endif



trigger store
store
if ($status <0)
   message $text(1500) ;error
   rollback
else
   if ($status = 1)
      message $text(1723) ;no change
   else
      commit
      if ($status < 0)
         rollback
      else
         message $text(1805) ;OK
      endif
   endif
endif



trigger retrieveSequential
retrieve
if ($status <0)
   message $text(1765) ;error
endif



trigger retrieve
retrieve
if ($status < 0)
   message $text(1762) ;error
endif



trigger clear
clear



#startdefine

#define $triggerAbbr=LPMX
;ERROR CHECKS ADDED
;Added by ANDY REYNOLDS Date:19-02-2013 Time:15:40:21
entry LP_ERROR
	params
		string PV_ERROR:INOUT
	endparams
	variables
		string TV_LIST,TV_LANG,TV_INSTANCE,TV_ERROR_TEXT,TV_DATASTREAM,TV_TEXT
	endvariables

	if (PV_ERROR = "")
		return(-1)
	endif
	newinstance "GSSESSION", TV_INSTANCE
	#include NTIER:CHECK_ERROR
	activate TV_INSTANCE.GET_SESSION ($LV_SESS_MESS$, "LANGUAGE", TV_LANG)
	#include NTIER:CHECK_ERROR
	deleteinstance TV_INSTANCE
	if (TV_LANG = "")
		return(-1)
	endif

	TV_LIST = "ID=%%PV_ERROR%%%[[uSEP]]LANGUAGE=%%TV_LANG%%%"
	activate "GSVALIDATE".EXISTS ($LV_SESS_MESS$, "EMANMESS", "", TV_LIST)
	#include NTIER:CHECK_ERROR
	if ($status = 0)
	    getitem/id PV_ERROR, TV_LIST, "MESSAGE"
	endif
	return(0)


entry LP_PROCESS_INPUT
params
	string PV_LOGIN:IN	
	string PV_INPUT:IN
	string PV_PAYLOAD:OUT
endparams
variables
	string TV_LIST
	struct TV_STRUCT
	numeric TV_SCAN ; MRB 28/04/26 SPR # 103472
endvariables

	; MRB 28/04/26 SPR # 103472 - web calls coming in with an empty body causes infinite loop
	TV_SCAN = $scan(PV_INPUT, "text/json")
	if (TV_SCAN > 0) && ($item("text/json", PV_INPUT) = "") return (-10)

;mmb spr-82697 - re-instated code (from spr-82323)
    if ($item("text/json",PV_INPUT)!="")
;		TV_LIST = "%%$valuepart(PV_INPUT)%%%="
		TV_LIST = $valuepart(PV_INPUT)
		jsontostruct TV_STRUCT, TV_LIST 
		if ($status<0) ; Fallback... Strange JSON that somehow works
			call LP_JSON2LIST(PV_LOGIN,TV_LIST,PV_PAYLOAD)   
			#include NTIER:CHECK_ERROR
		endif
		call LP_STRUCT2LIST(TV_STRUCT->*,PV_PAYLOAD)

		; MRB 28/04/26 SPR # 103472 
		if (PV_PAYLOAD = "") return (-10)

		return 0 
    else 
		call LP_JSON2LIST(PV_LOGIN,PV_INPUT,PV_PAYLOAD) ; then fallback on Mobile malformed JSON that has a "=" at the end
		#include NTIER:CHECK_ERROR
	endif
end




entry LP_PROCESS_OUTPUT
params
	string PV_OUTPUT:IN
	string PV_WEBOUTPUT:OUT
endparams
	call LP_LIST2JSON(PV_OUTPUT,<GC_FALSE>,PV_WEBOUTPUT)
	#include NTIER:CHECK_ERROR
	PV_WEBOUTPUT="{%%PV_WEBOUTPUT%%%}"
end

entry LP_LIST2JSON
	params
		string PV_LIST :IN
		boolean PV_SINGLE_OBJECT:IN ;SPR #70121/70663 28/08/2013 GS - Need to handle multiple occurences in a list
		string PV_JSON:OUT
	endparams
	variables
		string TV_ID, TV_VALUE,TV_INSTANCE
	endvariables
	newinstance "GSSTRINGFUNC", TV_INSTANCE ;spr 70121
	while (PV_LIST !="")
		TV_ID=$idpart($itemnr(1,PV_LIST))	
		TV_value=$valuepart($itemnr(1,PV_LIST))	
;spr 70121 start
;		activate "GSSTRINGFUNC".JSCRIPT_ESCAPE(TV_ID)	
		activate TV_INSTANCE.JSCRIPT_ESCAPE(TV_ID)
		#include NTIER:CHECK_ERROR		
;		activate "GSSTRINGFUNC".JSCRIPT_ESCAPE(TV_VALUE)	
		activate TV_INSTANCE.JSCRIPT_ESCAPE(TV_VALUE)	
		#include NTIER:CHECK_ERROR
;spr 70121 end

		;SPR #70121/70663 28/08/2013 GS - Cater for a single object output
		if (PV_SINGLE_OBJECT == <GC_TRUE>)
			PV_JSON="%%PV_JSON%%% %%TV_ID%%%:%%"%%TV_VALUE%%%%%""
		else
			PV_JSON="%%PV_JSON%%% %%"%%TV_ID%%%%%":%%"%%TV_VALUE%%%%%""
		endif
		delitem PV_LIST,1
		if (PV_LIST!="")
			PV_JSON="%%PV_JSON%%%,  %%^ "
		endif
	endwhile

	deleteinstance TV_INSTANCE
	TV_INSTANCE = ""
	return(0)
end


entry LP_JSON2LIST
	params
		string PV_LOGIN:IN	
		string PV_JSON:IN
		string PV_LIST :OUT
	endparams
	variables
		string  TV_LIST_WITHIN,TV_FINAL_LIST,TV_DATA
		numeric TV_START, TV_END,TV_JASONFORMAT,TV_START_SQUARE,TV_END_SQUARE 
		string  TV_STRING,TV_LAST_CHARACTER
		numeric TV_LENGTH
		;SPR#79485
		string  TV_RIGHT
		string  TV_LEFT
		string  TV_LOOKFOR
		numeric TV_POSITION
		;SPR 79485 - END
		string TV_AUX	 ;SPR#87196
	endvariables

	;SPR#87196 - Replacement of " in "fields" section - lUIS bURON - 27/02/2017
	TV_AUX = PV_JSON
	TV_START = $scan(TV_AUX, "fields%%"%%%:{%%"%%%")
	if (TV_START > 0)
		TV_START = TV_START + 9
		TV_LEFT = PV_JSON[1,TV_START]
		TV_START = TV_START + 1
		TV_AUX = PV_JSON[TV_START]
		TV_AUX = $replace(TV_AUX,1,"%%"%%%:%%"%%%","<@1@>",-1)
		TV_AUX = $replace(TV_AUX,1,"%%"%%%,%%"%%%","<@2@>",-1)
		;SPR#88424
		TV_AUX = $replace(TV_AUX,1,"%%"%%%}","<@5@>",-1)
		;SPR 88424
		TV_AUX = $replace(TV_AUX,1,"%%"%%%:","<@3@>",-1)
		TV_AUX = $replace(TV_AUX,1,",%%"%%%","<@4@>",-1)
		TV_AUX = $replace(TV_AUX,1,"\\","<@DBSLA@>",-1)
		TV_AUX = $replace(TV_AUX,1,"\%%"%%%","<@DBQUOTE@>",-1)
		TV_AUX = $replace(TV_AUX,1,"%%"%%%","<@DBQUOTE@>",-1)
		TV_AUX = $replace(TV_AUX,1,"<@1@>","%%"%%%:%%"%%%",-1)
		TV_AUX = $replace(TV_AUX,1,"<@2@>","%%"%%%,%%"%%%",-1)
		;SPR#88424
		TV_AUX = $replace(TV_AUX,1,"<@5@>","%%"%%%}",-1)
		;SPR 88424
		TV_AUX = $replace(TV_AUX,1,"<@3@>","%%"%%%:",-1)
		TV_AUX = $replace(TV_AUX,1,"<@4@>",",%%"%%%",-1)
		PV_JSON = "%%TV_LEFT%%%%%TV_AUX%%%"
		TV_LEFT=""
	endif
	;SPR 87196 - END

	;SPR#79485 - Avoid wrong replacement for some characters - Luis Buron - 24/02/2015
	TV_LOOKFOR ='""'
	TV_LOOKFOR = TV_LOOKFOR[1:1]
	TV_POSITION=1
	while (TV_POSITION>0)	
		TV_POSITION=$split(PV_JSON,1, TV_LOOKFOR,TV_LEFT,TV_RIGHT)
		TV_POSITION=$split(TV_RIGHT,1,TV_LOOKFOR,TV_STRING,TV_RIGHT)
		if (TV_POSITION>0)		
			;Replaces in TV_STRING
			TV_STRING = $replace(TV_STRING,1,"\\","<@DBSLA@>",-1)
			TV_STRING= $replace(TV_STRING,1,"\%%"%%%","<@DBQUOTE@>",-1)
			TV_STRING = $replace(TV_STRING,1,":","<@COLON@>",-1)
			TV_STRING= $replace(TV_STRING,1,",","<@COMMA@>",-1)
			TV_STRING= $replace(TV_STRING,1,"%%"","<@DBPER@>",-1)
			TV_STRING = $replace(TV_STRING,1,"%%^","<@BRRET@>",-1)
			TV_STRING = $replace(TV_STRING,1,"	","<@DBSPA@>",-1)
			PV_JSON = "%%TV_LEFT%%%<@DBQUO@>%%TV_STRING%%%<@DBQUO@>%%TV_RIGHT%%%"
			TV_POSITION = $scan(PV_JSON,TV_LOOKFOR)
		endif
	endwhile 	
	PV_JSON = $replace(PV_JSON,1,"<@DBQUO@>",TV_LOOKFOR,-1)	
	TV_STRING=""
	;SPR 79485 - Luis Buron - 24/02/2015 - END

	getitem/id TV_DATA,PV_JSON,"DATA"
	if ($status > 0)
		PV_JSON = $item("DATA",PV_JSON)
		TV_START = $scan(PV_JSON, "{")
		TV_END = $scan(PV_JSON, "}")

		; MRB 16/04/26 SPR # 103447
;		if(TV_START = 0 & TV_END =  0)
;			return(-1)
;		endif
		if ( (TV_START = 0) || (TV_END = 0) ) return (-1)

	endif

	PV_JSON = $replace(PV_JSON,1,"%%^%%%","",-1)
	PV_JSON = $replace(PV_JSON,1,"	","",-1)
	PV_JSON = PV_JSON[3:$length(PV_JSON)]
	TV_LENGTH= $length(PV_JSON)
	while (TV_LENGTH > 0)
		TV_LAST_CHARACTER = PV_JSON[TV_LENGTH:TV_LENGTH]
		scan TV_LAST_CHARACTER,"="
		if ($result = 1)
			PV_JSON = PV_JSON[1:$length(PV_JSON)-1]
		endif
		scan TV_LAST_CHARACTER," "
		if ($result = 1)
			PV_JSON = PV_JSON[1:$length(PV_JSON)-1]
		endif
		scan TV_LAST_CHARACTER,")"
		if ($result = 1)
			PV_JSON = PV_JSON[1:$length(PV_JSON)-1]
		endif
		scan TV_LAST_CHARACTER,"}"
		if ($result = 1)
			PV_JSON = PV_JSON[1:$length(PV_JSON)-1]
			break
		endif
		TV_LENGTH = $length(PV_JSON)
	endwhile

	;spr 70121 start
	TV_START = $scan(PV_JSON, "[")
	TV_END = $scan(PV_JSON, "]")
	if(TV_START <= 0 & TV_END <= 0)
		TV_START = $scan(PV_JSON, "{")
		TV_END = $scan(PV_JSON, "}")
		TV_LIST_WITHIN = PV_JSON[TV_START + 1,TV_END - 1]
	else ;we have a list!
		TV_LIST_WITHIN = PV_JSON[TV_START + 1,TV_END - 1]
		TV_LIST_WITHIN = $replace(TV_LIST_WITHIN, 1, "%%"%%%,%%"%%%", "[[uNOT]]%%"%%%,%%"%%%", -1)
	endif
	if(TV_START > 0 & TV_END > 0)
		TV_LIST_WITHIN = $replace(TV_LIST_WITHIN,1,":","=",-1)
		TV_LIST_WITHIN = $replace(TV_LIST_WITHIN,1,",","[[uNOT]][[uSEP]]",-1)
		TV_LIST_WITHIN = $replace(TV_LIST_WITHIN,1,"%%"","",-1)
		TV_LIST_WITHIN = $replace(TV_LIST_WITHIN,1,"}","",-1)
		TV_LIST_WITHIN = $replace(TV_LIST_WITHIN,1,"{","",-1)
	;spr 70121 end
	endif
	PV_LIST = "%%PV_JSON[1,TV_START - 1]%%%%%TV_LIST_WITHIN%%%%%PV_JSON[TV_END + 1]%%%"
	PV_LIST= $replace(PV_LIST,1,":","=",-1)
	PV_LIST= $replace(PV_LIST,1,",","[[uSEP]]",-1)
	PV_LIST= $replace(PV_LIST,1,"%%"","",-1)
	PV_LIST = $replace(PV_LIST,1,"%%^","",-1)
	PV_LIST = $replace(PV_LIST,1,"	","",-1)
	;SPR#87160 - Manage also \r and strings like '\nwhatever' - Luis Buron - 17/02/2017
	PV_LIST = $replace(PV_LIST,1,"\r\n","%%^",-1)
	;SPR 87160 - END
	;spr 70121 start
	PV_LIST = $replace(PV_LIST,1,"\n","%%^",-1)
	;spr 70121 end
	;SPR#87160 - Manage also \r and strings like '\nwhatever' - Luis Buron - 17/02/2017
	PV_LIST = $replace(PV_LIST,1,"\r","%%^",-1)
	;SPR 87160 - END

	;SPR#79485 - Luis Buron - 24/02/2015
	PV_LIST= $replace(PV_LIST,1,"<@COLON@>",":",-1)
	PV_LIST= $replace(PV_LIST,1,"<@COMMA@>",",",-1)
	PV_LIST= $replace(PV_LIST,1,"<@DBPER@>","%%"",-1)
	PV_LIST = $replace(PV_LIST,1,"<@BRRET@>","%%^",-1)
	PV_LIST = $replace(PV_LIST,1,"<@DBSPA@>","	",-1)
	;SPR#87160 - Manage also \r and strings like '\nwhatever' - Luis Buron - 17/02/2017
	PV_LIST = $replace(PV_LIST,1,"<@DBSLA@>","\",-1)
	;SPR 87160 - END
	;SPR#87196
	PV_LIST = $replace(PV_LIST,1,"<@DBQUOTE@>","%%"%%%",-1)
	;SPR 87196 - END
	;SPR 79485 - 24/02/2015 - END

	return(0)
end ;LP_JSON2LIST


;SPR #70121/70663 28/08/2013 GS - Need to handle multiple occurences in a list
entry LP_PROCESS_MULTIPLE_OUTPUT
	params
		string  PV_OUTPUT:IN
		boolean PV_SINGLE_OBJECT:IN
		string  PV_WEBOUTPUT:OUT
	endparams
	variables
		string TV_ITEM
		numeric TV_POSITION
	endvariables

	TV_POSITION = 1
	getitem TV_ITEM, PV_OUTPUT, TV_POSITION
	
	if (PV_SINGLE_OBJECT == <GC_TRUE>)
		PV_WEBOUTPUT = "[{"
	else
		PV_WEBOUTPUT = "["
	endif

	while (TV_ITEM != <GC_NULL>)
;		if (PV_WEBOUTPUT != "%%^[" && PV_WEBOUTPUT[$length(PV_WEBOUTPUT)] != "[")
		if (PV_WEBOUTPUT[$length(PV_WEBOUTPUT)] != "[" && PV_WEBOUTPUT != "[{")
			PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,",")
		endif

		if ($scan(TV_ITEM, "[[uNOT]]") > 0)
			call LP_PROCESS_INNER_LIST(TV_ITEM,PV_SINGLE_OBJECT,TV_ITEM)
			#include NTIER:CHECK_ERROR
		else
			call LP_LIST2JSON(TV_ITEM,PV_SINGLE_OBJECT,TV_ITEM)
			#include NTIER:CHECK_ERROR
		endif
		if (PV_SINGLE_OBJECT)
			PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,TV_ITEM)
		else
			PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,"%%^{%%^", TV_ITEM,"%%^}%%^")
		endif
		TV_POSITION = (TV_POSITION + 1)
		getitem TV_ITEM, PV_OUTPUT, TV_POSITION
	endwhile

	if (PV_SINGLE_OBJECT == <GC_TRUE>)
		PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,"}]")
	else
		PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,"]")
	endif
	return (<GC_OK>)
end

;SPR #70121/70663 28/08/2013 GS - Need to handle multiple occurences in a list
entry LP_PROCESS_INNER_LIST
	params
		string  PV_OUTPUT:IN
		boolean PV_SINGLE_OBJECT:IN
		string  PV_WEBOUTPUT:OUT
	endparams
	variables
		string  TV_FIELD
		string  TV_VALUE
		string  TV_ITEM
		numeric TV_POSITION
		numeric TV_SPLIT
	endvariables
	

	$result = $split(PV_OUTPUT, 1, "=", TV_FIELD, TV_VALUE)
	TV_POSITION = 1
	if (PV_SINGLE_OBJECT)
		PV_WEBOUTPUT = "%%TV_FIELD%%%: ["
	else
		PV_WEBOUTPUT = "%%"%%%%%TV_FIELD%%%%%"%%%: ["
	endif
	if (($scan(TV_VALUE, "=") == 0) && ($scan(TV_VALUE, "[[uNOT]][[uSEP]]") != 0)) ;Associative list
		TV_VALUE = $replace(TV_VALUE,1,"[[uNOT]][[uSEP]]","[[uSEP]]",-1)
		getitem TV_ITEM, TV_VALUE, TV_POSITION
		while (TV_ITEM != <GC_NULL>)
			if (PV_WEBOUTPUT[$length(PV_WEBOUTPUT)] != "[") PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,",")
			if ($scan(TV_ITEM, "[[uNOT]][[uSEP]]") > 0)
				call LP_PROCESS_INNER_LIST(TV_ITEM,PV_SINGLE_OBJECT,TV_ITEM)
				#include NTIER:CHECK_ERROR
			endif
			PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,"%%"%%%",TV_ITEM,"%%"%%%")
			TV_POSITION = (TV_POSITION + 1)
			getitem TV_ITEM, TV_VALUE, TV_POSITION
		endwhile
	else ; indexed list
		getitem TV_ITEM, TV_VALUE, TV_POSITION
		while (TV_ITEM != <GC_NULL>)
;			if (PV_WEBOUTPUT != "%%"%%%%%TV_FIELD%%%%%"%%%: [")
			if (PV_WEBOUTPUT[$length(PV_WEBOUTPUT)] != "[")
				PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,",")
			endif
			if ($scan(TV_ITEM, "[[uNOT]][[uSEP]]") > 0)
				call LP_PROCESS_INNER_LIST(TV_ITEM,PV_SINGLE_OBJECT,TV_ITEM)
				#include NTIER:CHECK_ERROR
			endif

			call LP_LIST2JSON(TV_ITEM,PV_SINGLE_OBJECT,TV_ITEM)
			#include NTIER:CHECK_ERROR

			PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,"%%^{%%^", TV_ITEM,"%%^}%%^")
			TV_POSITION = (TV_POSITION + 1)
			getitem TV_ITEM, TV_VALUE, TV_POSITION
		endwhile
	endif
	PV_WEBOUTPUT = $concat(PV_WEBOUTPUT,"]")
	return (<GC_OK>)
end

;SPR#79485 - Luis Buron - 24/02/2015 
;This local procedure was missing
entry LP_ENCODE
	params
		string PV_STRING	: INOUT
	endparams
	if ($LV_GSSTRINGFUNC$ == <GC_NULL>)
		newinstance "GSSTRINGFUNC", $LV_GSSTRINGFUNC$
		if ($status < 0)
			activate "GSSTRINGFUNC".JSCRIPT_ESCAPE(PV_STRING)
			if ($status < 0) return (<GC_STOP>)
		endif
	endif
	$LV_GSSTRINGFUNC$->JSCRIPT_ESCAPE(PV_STRING)
	if ($status < 0)
		activate "GSSTRINGFUNC".JSCRIPT_ESCAPE(PV_STRING)
		if ($status < 0) return (<GC_STOP>)
	endif
	return (<GC_OK>) 
end ;LP_ENCODE

;Inform the Audit Trail, user has logged on
entry LP_AUDIT_LOGIN
	params
		string  PV_MESSAGE :INOUT
		numeric PV_ULEVEL  :IN
	endparams
	variables
		string TV_BEFORE
		string TV_AFTER
		string TV_KEYS
		string TV_FIELD
		string TV_VALUE
		string TV_NEWROW
		string TV_PARAMS
		string TV_FNAME
		string TV_SNAME
		string TV_SCREEN
		string TV_STATUS
		string TV_FIELDFROM
		string TV_VALUEFROM
		string TV_VALUETO
		string TV_SERVERCONTEXT, TV_SERVERVARIABLES, TV_IPADDRESS, TV_USERNAME ; SPR #101460 - 18/10/2023 - Jon Clark
		boolean TV_ADD_SESS_ID ; SPR #101460 - 24/10/2023 - Jon Clark
	endvariables
	
	putitem/id TV_PARAMS, "ENAME",      "LOGIN"
	putitem/id TV_PARAMS, "SNAME",      "SPDEDJSONSERVICE"

	; SPR #101460 - 18/10/2023 - Jon Clark
	; get all of the variables
	call GP_APIAUDITVARS($LV_SESS_ID$, TV_SERVERCONTEXT, TV_IPADDRESS, TV_USERNAME)
	; SPR #101460 - 18/10/2023 - END

	; MRB 02/03/16 SPR # 82323
;	putitem/id TV_PARAMS, "SCREEN",     "Manhattan Mobile Password Entry"
	if ($item("text/json", $webinfo("input")) != "")
		putitem/id TV_PARAMS, "SCREEN", "API Password Entry"
	else
		putitem/id TV_PARAMS, "SCREEN", "Manhattan Mobile Password Entry"
	endif
	; End MRB

	putitem/id TV_PARAMS, "TRAIL_TYPE", "LOGIN"
	putitem/id TV_PARAMS, "PK",         "LOGIN"
	if (PV_ULEVEL = 9)
		; SPR #101460 - 18/10/2023 - Jon Clark
		;putitem/id TV_PARAMS, "MESSAGE", "Logged in with an authorisation level of %%PV_ULEVEL%%% - Super User."
		putitem/id TV_PARAMS, "MESSAGE", $concat("Logged in with an authorisation level of %%PV_ULEVEL%%% - Super User.", "%%^", TV_SERVERCONTEXT)
		; SPR #101460 - 18/10/2023 - END
	else
		; SPR #101460 - 18/10/2023 - Jon Clark
		;putitem/id TV_PARAMS, "MESSAGE", "Logged in with an authorisation level of %%PV_ULEVEL%%%."
		putitem/id TV_PARAMS, "MESSAGE", $concat("Logged in with an authorisation level of %%PV_ULEVEL%%%.", "%%^", TV_SERVERCONTEXT)
		; SPR #101460 - 18/10/2023 - END
	endif
	putitem/id TV_PARAMS, "DESC",       ""
	putitem/id TV_PARAMS, "FNAME",      "LOGON"
	; SPR #101460 - 18/10/2023 - Jon Clark
	;putitem/id TV_PARAMS, "FIELD_FROM", ""
	;putitem/id TV_PARAMS, "FIELD_TO",   ""
	putitem/id TV_PARAMS, "FIELD_FROM", $LV_SESS_ID$
	putitem/id TV_PARAMS, "FIELD_TO",   TV_IPADDRESS
	; SPR #101460 - 18/10/2023 - END

	
	activate "BSAUDITTRAIL".LOGIT(PV_MESSAGE, TV_PARAMS)
	#include NTIER:CHECK_ERROR
	if ($status=<GC_OK>)
		commit
	endif

	return <GC_OK>
end ;LP_AUDIT_LOGIN
;SPR 79485 - 24/02/2015 - END				

; #SPR 101460 - 06/10/2023 - Jon Clark
; Inform the Audit Trail, that there has been a failure to logon
entry LP_AUDIT_LOGIN_FAIL
	params
		string  PV_MESSAGE :INOUT
		numeric PV_ULEVEL  :IN
	endparams
	variables
		string TV_BEFORE, TV_AFTER, TV_KEYS, TV_FIELD, TV_VALUE, TV_NEWROW, TV_PARAMS, TV_FNAME
		string TV_SNAME, TV_SCREEN, TV_STATUS, TV_FIELDFROM, TV_VALUEFROM, TV_VALUETO
		string TV_SESS_ID, TV_SERVERCONTEXT, TV_SERVERVARIABLES, TV_IPADDRESS, TV_REQUEST, TV_DESC, TV_USERNAME ; SPR #101460 - 18/10/2023 - Jon Clark
		boolean TV_ADD_SESS_ID ; SPR #101460 - 18/10/2023 - Jon Clark
	endvariables
	
	putitem/id TV_PARAMS, "ENAME",      "FAILURE"
	putitem/id TV_PARAMS, "SNAME",      "SPDEDJSONSERVICE"

	; SPR #101460 - 18/10/2023 - Jon Clark
	; get all of the variables
	call GP_APIAUDITVARS($LV_SESS_ID$, TV_SERVERCONTEXT, TV_IPADDRESS, TV_USERNAME)
	TV_USERNAME = LF_GETUSERNAME()
	; SPR #101460 - 18/10/2023 - END

	if ($item("text/json", $webinfo("input")) != "")
		putitem/id TV_PARAMS, "SCREEN", "API Password Entry"
	else
		putitem/id TV_PARAMS, "SCREEN", "Manhattan Mobile Password Entry"
	endif

	putitem/id TV_PARAMS, "TRAIL_TYPE", "LOGIN"
	putitem/id TV_PARAMS, "PK",         "LOGIN"
	putitem/id TV_PARAMS, "DESC",       "" ; add in extra information here
	putitem/id TV_PARAMS, "FNAME",      "LOGON"
	; SPR #101460 - 18/10/2023 - Jon Clark
	;putitem/id TV_PARAMS, "FIELD_FROM", ""
	;putitem/id TV_PARAMS, "FIELD_TO",   ""
	putitem/id TV_PARAMS, "USERNAME", TV_USERNAME

	putitem/id TV_PARAMS, "MESSAGE", $concat("User Failed to Login.", "%%^",  $webinfo("input"), "%%^", TV_SERVERCONTEXT)
	;putitem/id TV_PARAMS, "MESSAGE", $concat($webinfo("input"), "%%^", "TV_USERNAME=", TV_USERNAME)
	if ( TV_ADD_SESS_ID	)
		putitem/id TV_PARAMS, "FIELD_FROM", $LV_SESS_ID$
	endif
	putitem/id TV_PARAMS, "FIELD_TO",   TV_IPADDRESS
	; SPR #101460 - 18/10/2023 - END

	activate "BSAUDITTRAIL".LOGIT(PV_MESSAGE, TV_PARAMS)
	#include NTIER:CHECK_ERROR
	if ($status=<GC_OK>)
		commit
	endif

	return <GC_OK>
end ;LP_AUDIT_LOGIN_FAIL

entry LP_AUDIT_LOGOUT_FAIL
	params
		string  PV_MESSAGE :INOUT
	endparams
	variables
		string TV_BEFORE, TV_AFTER, TV_KEYS, TV_FIELD, TV_VALUE, TV_NEWROW, TV_PARAMS, TV_FNAME
		string TV_SNAME, TV_SCREEN, TV_STATUS, TV_FIELDFROM, TV_VALUEFROM, TV_VALUETO
		string TV_SESS_ID, TV_SERVERCONTEXT, TV_SERVERVARIABLES, TV_IPADDRESS, TV_REQUEST, TV_DESC, TV_USERNAME ; SPR #101460 - 18/10/2023 - Jon Clark
		boolean TV_ADD_SESS_ID ; SPR #101460 - 18/10/2023 - Jon Clark
	endvariables
	
	putitem/id TV_PARAMS, "ENAME",      "FAILURE"
	putitem/id TV_PARAMS, "SNAME",      "SPDEDJSONSERVICE"

	; get all of the variables
	call GP_APIAUDITVARS($LV_SESS_ID$, TV_SERVERCONTEXT, TV_IPADDRESS, TV_USERNAME)
	TV_USERNAME = LF_GETUSERNAME()
	; SPR #101460 - 18/10/2023 - END

	if ($item("text/json", $webinfo("input")) != "")
		putitem/id TV_PARAMS, "SCREEN", "API Logout"
	else
		putitem/id TV_PARAMS, "SCREEN", "Manhattan Logout"
	endif

	putitem/id TV_PARAMS, "TRAIL_TYPE", "LOGOUT"
	putitem/id TV_PARAMS, "PK",         "LOGOUT"
	putitem/id TV_PARAMS, "DESC",       "" ; add in extra information here
	putitem/id TV_PARAMS, "FNAME",      "LOGOUT"
	; SPR #101460 - 18/10/2023 - Jon Clark
	;putitem/id TV_PARAMS, "FIELD_FROM", ""
	;putitem/id TV_PARAMS, "FIELD_TO",   ""
	putitem/id TV_PARAMS, "USERNAME", TV_USERNAME

	if ($LV_SESS_ID$ == <GC_NULL>)
		putitem/id TV_PARAMS, "MESSAGE", $concat("No session ID.", "%%^",  $webinfo("input"), "%%^", TV_SERVERCONTEXT)
	else
		putitem/id TV_PARAMS, "MESSAGE", $concat("Invalid session ID.", "%%^",  $webinfo("input"), "%%^", TV_SERVERCONTEXT)
	endif
	;putitem/id TV_PARAMS, "MESSAGE", $concat($webinfo("input"), "%%^", "TV_USERNAME=", TV_USERNAME)
	if ( TV_ADD_SESS_ID	)
		putitem/id TV_PARAMS, "FIELD_FROM", $LV_SESS_ID$
	endif
	putitem/id TV_PARAMS, "FIELD_TO",   TV_IPADDRESS
	; SPR #101460 - 18/10/2023 - END

	activate "BSAUDITTRAIL".LOGIT_API(PV_MESSAGE, TV_PARAMS)
	#include NTIER:CHECK_ERROR
	if ($status=<GC_OK>)
		commit
	endif

	return <GC_OK>
end ;LP_AUDIT_LOGOUT_FAIL

; #SPR 101460 - 06/10/2023 - END		

entry  LP_STRUCT2LIST
	params 
		struct TV_STRUCT : IN
		string TV_LIST   :INOUT
	endparams
	variables
		string TV_ITEM
		numeric TV_LOOP
	endvariables
	TV_LOOP=1
	while (TV_LOOP<=TV_STRUCT->$collsize)
		if (TV_STRUCT{TV_LOOP}->$isleaf)
			if (TV_STRUCT{TV_LOOP}->$name!="")
				putitem/id TV_LIST,TV_STRUCT{TV_LOOP}->$name,TV_STRUCT{TV_LOOP}->*
			else
				putitem TV_LIST,-1,TV_STRUCT{TV_LOOP}
			endif
		else
			call LP_struct2list (TV_STRUCT{TV_LOOP}->*,TV_ITEM)
			if (TV_STRUCT{TV_LOOP}->$name!="")
				putitem/id TV_LIST,TV_STRUCT{TV_LOOP}->$name,TV_ITEM
			else
				putitem TV_LIST,-1,TV_ITEM
				
			endif
		endif
		TV_LOOP=TV_LOOP+1
	endwhile
	
end

;SPR #94093 24/04/2019 GS - Yet another nested list to JSON builder to rule all others. (nice LOR reference :))
entry LF_PROCESS_OUTPUT
	returns string
	params
		string  PV_LIST	: IN
		boolean PV_ARRAY	: IN ;List is an array (otherwise it is an object)
	endparams
	variables
		string  TV_JSON
	endvariables
	if (PV_ARRAY)
		structToJson TV_JSON, LF_ARRAY_TO_STRUCT(PV_LIST)
		#include NTIER:CHECK_ERROR
	else
		structToJson TV_JSON, LF_OBJECT_TO_STRUCT(PV_LIST)
		#include NTIER:CHECK_ERROR
	endif
	return TV_JSON
end ;LF_PROCESS_OUTPUT

entry LF_ARRAY_TO_STRUCT
	returns struct
	params
		string  PV_LIST	: IN
	endparams
	variables
		numeric TV_POS
		string  TV_ITEM
		struct  TV_STRUCT
	endvariables
	TV_STRUCT = $newStruct
	TV_STRUCT->$tags->jsonClass = "array"
	forlist TV_ITEM, TV_POS in PV_LIST
		if ($valuepart(TV_ITEM) != TV_ITEM)
			TV_STRUCT->*{TV_POS} = LF_OBJECT_TO_STRUCT(TV_ITEM)
		elseif ($itemcount(TV_ITEM) > 1)
			TV_STRUCT->*{TV_POS} = LF_ARRAY_TO_STRUCT(TV_ITEM)
		else
			TV_STRUCT->*{TV_POS} = TV_ITEM
		endif
	endfor
	return TV_STRUCT
end ;LF_ARRAY_TO_STRUCT

entry LF_OBJECT_TO_STRUCT
	returns struct
	params
		string  PV_LIST	: IN
	endparams
	variables
		string  TV_IDPART, TV_VALUEPART
		struct  TV_STRUCT
	endvariables
	TV_STRUCT = $newStruct
	TV_STRUCT->$tags->jsonClass = "object"
	forlist/id TV_IDPART, TV_VALUEPART in PV_LIST
		if ($valuepart(TV_VALUEPART) != TV_VALUEPART)
			TV_STRUCT->"%%TV_IDPART%%%" = LF_OBJECT_TO_STRUCT(TV_VALUEPART)
		elseif ($itemcount(TV_VALUEPART) > 1)
			TV_STRUCT->"%%TV_IDPART%%%" = LF_ARRAY_TO_STRUCT(TV_VALUEPART)
		else
			TV_STRUCT->"%%TV_IDPART%%%" = TV_VALUEPART
		endif
	endfor
	return TV_STRUCT
end ;LF_OBJECT_TO_STRUCT

entry LP_CLEAR_COOKIE
	variables
		string  TV_REQUEST_URI, TV_SERVLET_PATH, TV_SERVERVARIABLES, TV_COOKIESOUT, TV_PATH
		numeric    TV_FROM
	endvariables
	
	getitem/id TV_SERVERVARIABLES, $webinfo("webservercontext"), "SERVERVARIABLES"
	getitem/id TV_REQUEST_URI, TV_SERVERVARIABLES, "REQUEST_URI"
	getitem/id TV_SERVLET_PATH, TV_SERVERVARIABLES, "SERVLET_PATH"
	if(TV_REQUEST_URI != "" & TV_SERVLET_PATH != "")
		TV_FROM = $scan(TV_REQUEST_URI, TV_SERVLET_PATH)
		putitem/id TV_PATH, "path", TV_REQUEST_URI[1,TV_FROM]
	endif

	; Jon C - error checking
	; need to check the payload for text/plain
	
;SPR #69506 05/06/2013 GS - Ensure cookie is cleared for Uniface 9
	#if ( <UNIFACEVERS> == 9 )
		;SPR #76307/76539 24/10/2014 GS - Clear session when using container based security (Logout needs to destroy the container's session)
		if ($uppercase($logical("SSO_MODE"))="TOMCAT_JNDI" && ($logical("SSO_LOGOUT_URL") == <GC_NULL>))
			;Invalidate session if no logout page is defined (otherwise the container session will still exist)
			$webinfo("UserContext") = "1[[uSEP]]httponly=F[[uSEP]]%%TV_PATH%%%"
			TV_COOKIESOUT = "UwdSessionID=1[[uNOT]][[uSEP]]httponly=F"
		else ;SPR 76307 ends (perhaps expires=0 should be set below?)
			$webinfo("UserContext") = "[[uSEP]]httponly=F[[uSEP]]%%TV_PATH%%%"
			TV_COOKIESOUT = "UwdSessionID=[[uNOT]][[uSEP]]httponly=F"
		endif
;SPR 69506 end
	#else
		;SPR #76307/76539 24/10/2014 GS - Clear session when using container based security (Logout needs to destroy the container's session)
		if ($uppercase($logical("SSO_MODE"))="TOMCAT_JNDI" && ($logical("SSO_LOGOUT_URL") == <GC_NULL>))
			;Invalidate session if no logout page is defined (otherwise the container session will still exist)
			$webinfo("UserContext") = "1"
			TV_COOKIESOUT = "UwdSessionID=1"
		else ;SPR 76307 ends (perhaps expires=0 should be set below?)
			$webinfo("UserContext") = ""
			TV_COOKIESOUT = "UwdSessionID="
		endif
	#endif
	if(TV_PATH != "")
		TV_COOKIESOUT = "%%TV_COOKIESOUT%%%[[uNOT]][[uSEP]]%%TV_PATH%%%"
	endif
	
	$webinfo("cookiesout") = TV_COOKIESOUT
	
	return <GC_OK>
	
end ;LP_CLEAR_COOKIE


; SPR #101460 - 19/10/2023 - Jon Clark
; Inform the Audit Trail, that something has failed
entry LP_AUDIT_FAIL
	params
		string  PV_MESSAGE 			: INOUT
		string  PV_ULEVEL  			: IN
		string  PV_ERROR_MESSAGE 	: IN
	endparams
	variables
		string TV_BEFORE
		string TV_AFTER
		string TV_KEYS
		string TV_FIELD
		string TV_VALUE
		string TV_NEWROW
		string TV_PARAMS
		string TV_FNAME
		string TV_SNAME
		string TV_SCREEN
		string TV_STATUS
		string TV_FIELDFROM
		string TV_VALUEFROM
		string TV_VALUETO
		string TV_SESS_ID, TV_SERVERCONTEXT, TV_SERVERVARIABLES, TV_IPADDRESS, TV_REQUEST, TV_DESC, TV_USERNAME, TV_SESSIONID_PAYLOAD, TV_METHOD ; SPR #101460 - 18/10/2023 - Jon Clark
		boolean TV_ADD_SESS_ID ; SPR #101460 - 18/10/2023 - Jon Clark
	endvariables

	$LV_FAILURE$ = <GC_FALSE>
	
	putitem/id TV_PARAMS, "ENAME",      "FAILURE"
	putitem/id TV_PARAMS, "SNAME",      "SPDEDJSONSERVICE"


	; get all of the variables
	call GP_APIAUDITVARS($LV_SESS_ID$, TV_SERVERCONTEXT, TV_IPADDRESS, TV_USERNAME)
	TV_USERNAME = LF_GETUSERNAME()
	TV_METHOD= LF_GETMETHOD()
	; SPR #101460 - 18/10/2023 - END

	putitem/id TV_PARAMS, "TRAIL_TYPE", "DO"
	putitem/id TV_PARAMS, "PK",         "DO"
	putitem/id TV_PARAMS, "MESSAGE", $concat(PV_ERROR_MESSAGE, "%%^",  TV_SERVERCONTEXT, "%%^",  TV_REQUEST)
	putitem/id TV_PARAMS, "DESC",       ""
	putitem/id TV_PARAMS, "FNAME",      "DO"
	putitem/id TV_PARAMS, "FIELD_FROM", $LV_SESS_ID$
	putitem/id TV_PARAMS, "FIELD_TO",   TV_IPADDRESS
	putitem/id TV_PARAMS, "SCREEN",   TV_METHOD

	activate "BSAUDITTRAIL".LOGIT_API(PV_MESSAGE, TV_PARAMS)
	#include NTIER:CHECK_ERROR
	if ($status=<GC_OK>)
		commit
	endif

	return <GC_OK>
end ;LP_AUDIT_FAIL

entry LF_GETUSERNAME
	returns string
	variables
		struct TV_STRUCT
		string TV_USERNAME, TV_INPUT
	endvariables

	TV_INPUT = $replace($webinfo("input"), 1, "text/json=", "", 1)
	jsontostruct TV_STRUCT, TV_INPUT
	TV_USERNAME = TV_STRUCT->"username"->$scalar

	return TV_USERNAME

end ; LF_GETUSERNAME

entry LF_GETMETHOD
	returns string
	variables
		struct TV_STRUCT
		string TV_METHOD, TV_INPUT
	endvariables

	TV_INPUT = $replace($webinfo("input"), 1, "text/json=", "", 1)
	jsontostruct TV_STRUCT, TV_INPUT
	TV_METHOD = TV_STRUCT->"method"->$scalar

	return TV_METHOD

end ; LF_GETMETHOD

; Inform the Audit Trail, that something has failed
entry LP_AUDIT_SUCCESS
	params
		string  PV_MESSAGE : INOUT
		string  PV_ULEVEL  : IN
		string  PV_ERROR_MESSAGE : IN
		string  PV_OPERATION	:	IN
	endparams
	variables
		string TV_BEFORE
		string TV_AFTER
		string TV_KEYS
		string TV_FIELD
		string TV_VALUE
		string TV_NEWROW
		string TV_PARAMS
		string TV_FNAME
		string TV_SNAME
		string TV_SCREEN
		string TV_STATUS
		string TV_FIELDFROM
		string TV_VALUEFROM
		string TV_VALUETO
		string TV_SESS_ID, TV_SERVERCONTEXT, TV_SERVERVARIABLES, TV_IPADDRESS, TV_REQUEST, TV_DESC, TV_USERNAME ; SPR #101460 - 18/10/2023 - Jon Clark
		boolean TV_ADD_SESS_ID ; SPR #101460 - 18/10/2023 - Jon Clark
	endvariables
	
	putitem/id TV_PARAMS, "ENAME",      "SUCCESS"
	putitem/id TV_PARAMS, "SNAME",      "SPDEDJSONSERVICE"

	; SPR #101460 - 18/10/2023 - Jon Clark
	; get all of the variables
	call GP_APIAUDITVARS($LV_SESS_ID$, TV_SERVERCONTEXT, TV_IPADDRESS, TV_USERNAME)
	TV_USERNAME = LF_GETUSERNAME()
	; SPR #101460 - 18/10/2023 - END

	putitem/id TV_PARAMS, "TRAIL_TYPE", "DO"
	putitem/id TV_PARAMS, "PK",         "DO"
	putitem/id TV_PARAMS, "MESSAGE", $concat(PV_ERROR_MESSAGE, "%%^",  TV_SERVERCONTEXT, "%%^",  TV_REQUEST)
	putitem/id TV_PARAMS, "DESC",       ""
	putitem/id TV_PARAMS, "FNAME",      "DO"
	putitem/id TV_PARAMS, "FIELD_FROM", $LV_SESS_ID$
	putitem/id TV_PARAMS, "FIELD_TO",   TV_IPADDRESS
	putitem/id TV_PARAMS, "SCREEN", 	   PV_OPERATION
	
	activate "BSAUDITTRAIL".LOGIT_API(PV_MESSAGE, TV_PARAMS)
	#include NTIER:CHECK_ERROR
	if ($status=<GC_OK>)
		commit
	endif

	return <GC_OK>
end ;LP_AUDIT_SUCCESS

; SPR #101490 - 20/10/2023

#enddefine


#startdefine

#define $triggerAbbr=OPER
;ERROR CHECKS ADDED
;Added by ANDY REYNOLDS Date:19-02-2013 Time:15:40:21

#include U:zProcError  ; Report an unexpected failure in a proc statement.

; Jon C - This is called from the API Logout and Manhattan when you close a browser tab (or browser) - 29/11/2023
; API Logout has text/json
; Manhattan has text/plain
public operation LOGOUT
	public web
	variables
		string TV_PAYLOAD,TV_OUTPUT,TV_ERROR,TV_INSTANCE,TV_BSINSTANCE,TV_JSON
		string TV_CONTENT_TYPE ; SPR #101460 - 29/11/2023 - Jon Clark
		string TV_COOKIE_SESS
	endvariables

	variables
		string  TV_MESSAGE
		numeric TV_STATUS
	endvariables

	TV_COOKIE_SESS = $webinfo("usercontext")


	;SPR #87196 16/02/2017 GS - The new parser wasn't tested with the mobile, which was subsequently borken. Now adding a check to restore the old code if it looks like the old parser will work
	;;mmb spr-85806 21-sep-2016............
	;;orig
	;;	call LP_PROCESS_INPUT("T",$webinfo("input"),TV_PAYLOAD)
	;;	#include NTIER:CHECK_ERROR
	;;new
	;newinstance "BSJSON",TV_BSINSTANCE
	;activate TV_BSINSTANCE.OP_JSON2LIST2("","",$webinfo("input"),TV_PAYLOAD) ;mmb spr-86399, changed to use structs ie. from OP_JSON2LIST to OP_JSON2LIST2
	;#include NTIER:CHECK_ERROR
	;;mmb spr-85806 21-sep-2016 END


	if ($scan($webinfo("input"), $tometa(10)) == 0)
		call LP_PROCESS_INPUT("T",$webinfo("input"),TV_PAYLOAD)
		#include NTIER:CHECK_ERROR
	else
		newinstance "BSJSON",TV_BSINSTANCE
		activate TV_BSINSTANCE.OP_JSON2LIST2("","",$webinfo("input"),TV_PAYLOAD) ;mmb spr-86399, changed to use structs ie. from OP_JSON2LIST to OP_JSON2LIST2
		#include NTIER:CHECK_ERROR
	endif
	;SPR 87196 ends

	; SPR 101895 - Neil Payne - 28/03/24 - check API security
	TV_STATUS = $status
	if ( $uppercase($item("origin-app",TV_PAYLOAD)) != "MANHATTAN" )
		activate "BSAPISEC".VALIDATE_SECURITY(TV_MESSAGE)
		if ( $status < 0 )
			call LP_AUDIT_FAIL(<GC_NULL>, TV_PAYLOAD, TV_MESSAGE)
			#include NTIER:CHECK_ERROR

			putitem/id TV_OUTPUT,"success","false"
			putitem/id TV_OUTPUT,"message",TV_MESSAGE
			call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
			#include NTIER:CHECK_ERROR
			$webinfo("output")=TV_OUTPUT
			$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"
			$webinfo("STATUS")=401
			return <GC_STOP>
		endif
	endif
	$status = TV_STATUS
	;/101895

	if ($status = 0)
		deleteinstance TV_BSINSTANCE ;mmb spr-85806 21-sep-2016 END
		$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)
		newinstance "GSSESSION", TV_INSTANCE
		#include NTIER:CHECK_ERROR
		activate TV_INSTANCE."INIT_SESSION"($LV_SESS_MESS$,$LV_SESS_ID$,$LV_SESS$ )
		#include NTIER:CHECK_ERROR
		; SPR #101460 - 23/11/2023 - Jon Clark
		if ($status != 0) 
			; handle invalid session
			;if ($LV_SESS_ID$ = <GC_NULL>)
				call LP_AUDIT_LOGOUT_FAIL("") ;$LV_SESS_MESS$)
			;endif
			deleteinstance TV_BSINSTANCE ;mmb spr-85806 21-sep-2016 END
			putitem/id TV_OUTPUT,"success","false"
			putitem/id TV_OUTPUT,"message",""
			putitem/id TV_OUTPUT,"error","true"
			;spr 73518 start
			TV_ERROR = "UI111"
			putitem/id TV_OUTPUT,"errorId",TV_ERROR
		else
			; SPR #101460 - 23/11/2023 - END
			deleteinstance TV_INSTANCE
	;spr 73518 start
	;		TV_ERROR = "SEC0024"
			TV_ERROR = "UI109" ;Log out successful           
	;		call LP_ERROR(TV_ERROR)
	;spr 73518 end
			#include NTIER:CHECK_ERROR
			if ($LV_SESS_ID$ != <GC_NULL>)
				activate "BSDEMLOGIN"."LOGOUT"($LV_SESS_ID$,$LV_SESS_MESS$)
			endif
			#include NTIER:CHECK_ERROR
			if ($status = 0)
				putitem/id TV_OUTPUT,"success","true"
				putitem/id TV_OUTPUT,"message",""
				putitem/id TV_OUTPUT,"error","false"
	;spr 73518 start
				putitem/id TV_OUTPUT,"errorId",TV_ERROR
	;			putitem/id TV_OUTPUT,"errorText",TV_ERROR
	;spr 73518 start
			endif
		endif
	else
		deleteinstance TV_BSINSTANCE ;mmb spr-85806 21-sep-2016 END
		putitem/id TV_OUTPUT,"success","false"
		putitem/id TV_OUTPUT,"message",""
		putitem/id TV_OUTPUT,"error","true"
;spr 73518 start
		TV_ERROR = "UI111"
		putitem/id TV_OUTPUT,"errorId",TV_ERROR
;		putitem/id TV_OUTPUT,"errorText","Error encoding"
;spr 73518 start
	endif
	if (TV_OUTPUT)
		call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
		#include NTIER:CHECK_ERROR
	endif

	if ( $LV_SESS_ID$ != "" && TV_COOKIE_SESS != "" && $LV_SESS_ID$ == TV_COOKIE_SESS )
		; SPR 99720 - the cookies should be cleared when logging out.
		call LP_CLEAR_COOKIE()
		;/SPR 99720
	endif

	$webinfo("output")=TV_OUTPUT
	$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"
	$webinfo("UserContext") = "" ; SPR #101460 - 15/12/2023 - Neil Payne (dont change the cookie for API login/logout)
	
end ;LOGOUT


;SPR#82900 - Call GSSESSION.KeepAlive - Luis Buron - 16/12/2015
public operation KEEPALIVE
	public web
	variables
		string  TV_INSTANCE, TV_PAYLOAD, TV_ERROR, TV_OUTPUT
	endvariables

	;It expects the list "input", containing the input of the HTML request (in JSON) 
	;sent to SPDEDJSONSERVICE from the browser, includes the item "sessionID" with the value of the session Id.
	;f.i. $webinfo("input")={"sessionID":"7FA8768A-2F69-4E08-A70A-4169586117C1"}"

	call LP_PROCESS_INPUT("F",$webinfo("input"),TV_PAYLOAD)
	#include NTIER:CHECK_ERROR

	$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)

	if ($LV_SESS_ID$ != "")
		newinstance "GSSESSION", TV_INSTANCE
		#include NTIER:CHECK_ERROR
		activate "GSSESSION"."INIT_SESSION"($LV_SESS_MESS$ , $LV_SESS_ID$ , $LV_SESS$)
		#include NTIER:CHECK_ERROR
		if ($status = 0) 
			activate TV_INSTANCE."KEEPALIVE"($LV_SESS_MESS$)  
			#include NTIER:CHECK_ERROR
			deleteinstance TV_INSTANCE	
		else
			TV_ERROR  = "UI112" ;Error with Session ID
		endif
	else
		TV_ERROR  = "UI112" ;Error with Session ID
	endif
	if (TV_ERROR != "")
		putitem/id TV_OUTPUT,"error","true"
		putitem/id TV_OUTPUT,"errorId",TV_ERROR
		call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
		#include NTIER:CHECK_ERROR
		; SPR #101460 - 05/10/2023 - Jon Clark
		; PLACEHOLDER FOR LOGIN FAILURE
		; SPR #101460 - 05/10/2023 - END
	endif

	$webinfo("output")=TV_OUTPUT
	$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"

end ;KEEPALIVE
;SPR 82900 - END

; SPR #101460 - 29/11/2023 - This is only called from within the API - Jon Clark
public operation LOGIN
	public web
	variables
		string  TV_PAYLOAD,TV_OUTPUT, TV_DATA, TV_OPERATION, TV_OUTPUTMESSAGE,TV_LANG, TV_SPAREIN, TV_SPAREOUT,TV_CONTACT_DETAIL, TV_RLS,TV_CONTACT
		string  TV_ERROR,TV_PK, TV_USERNAME, TV_PASSWORD,TV_INSTANCE,TV_CREDENTIALS, TV_ROLE,TV_FULL_NAME, TV_LIST,TV_CONNECTIONPOOL,TV_LABEL_LANG,TV_USER_EMAIL
		;string  TV_USER   ;SPR#79485
		numeric TV_ULEVEL ;SPR#79485
		numeric TV_END,TV_COLON
		string  TV_API_KEY, TV_LOGICALAPIKEY, TV_BSINSTANCE, TV_WOPARTSOPT
		boolean TV_SUCCESS, TV_SSO_LOGIN
		struct  TV_OUTPUT_STRUCT
		string  TV_MESSAGE
	endvariables

	;SPR #87196 16/02/2017 GS - The new parser wasn't tested with the mobile, which was subsequently borken. Now adding a check to restore the old code if it looks like the old parser will work
	;; Magnus Mackay 28/06/16 #84581 - Added this logic - originally added by in v32 as follows (SPR 83599 Denis, introduce API key check)
	;TV_API_KEY=$item("api_key",$webinfo("HTTPREQUESTHEADERS"))
	;TV_LOGICALAPIKEY=$logical("API_KEY")
	;if (TV_LOGICALAPIKEY!="" & TV_LOGICALAPIKEY!=TV_API_KEY)
	;	putitem/id TV_OUTPUT,"success","false"
	;	putitem/id TV_OUTPUT,"message","Invalid API key"
	;	call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
	;	#include NTIER:CHECK_ERROR
	;	$webinfo("output")=TV_OUTPUT
	;	$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"
	;	$webinfo("STATUS")=403
	;	return <GC_STOP>
	;endif

	;;; Magnus Mackay 28/06/16 #84581 - Handle error status by initialising status boolean flag to false
	;TV_SUCCESS = 0

	;;mmb spr-85806 21-sep-2016............
	;;orig
	;;	call LP_PROCESS_INPUT("T",$webinfo("input"),TV_PAYLOAD)
	;;	#include NTIER:CHECK_ERROR
	;;new
	;newinstance "BSJSON",TV_BSINSTANCE
	;activate TV_BSINSTANCE.OP_JSON2LIST2("","",$webinfo("input"),TV_PAYLOAD) ;mmb spr-86399, changed to use structs ie. from OP_JSON2LIST to OP_JSON2LIST2
	;#include NTIER:CHECK_ERROR
	;;mmb spr-85806 21-sep-2016 END

	if ($scan($webinfo("input"), $tometa(10)) == 0)
		call LP_PROCESS_INPUT("T",$webinfo("input"),TV_PAYLOAD)
		#include NTIER:CHECK_ERROR
	else
		; 101895 - disable old API key technique if new one is enabled.
		sql "select AS_ENABLE_KEY from APISECURITY where AS_KEY = 'K'", "def"
		if ( $result < 1 ) 
			; Magnus Mackay 28/06/16 #84581 - Added this logic - originally added by in v32 as follows (SPR 83599 Denis, introduce API key check)
			TV_API_KEY=$item("api_key",$webinfo("HTTPREQUESTHEADERS"))
			TV_LOGICALAPIKEY=$logical("API_KEY")
			if (TV_LOGICALAPIKEY!="" & TV_LOGICALAPIKEY!=TV_API_KEY)
				putitem/id TV_OUTPUT,"success","false"
				putitem/id TV_OUTPUT,"message","Invalid API key"
				call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
				#include NTIER:CHECK_ERROR
				$webinfo("output")=TV_OUTPUT
				$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"
				$webinfo("STATUS")=403
				return <GC_STOP>
			endif
		endif

		; 101895 - Neil Payne - 28/03/24 - validate the API KEY and whitelist if set
		activate "BSAPISEC".VALIDATE_SECURITY(TV_MESSAGE)
		if ( $status < 0 )
			call LP_AUDIT_FAIL(<GC_NULL>, TV_PAYLOAD, TV_MESSAGE)
			#include NTIER:CHECK_ERROR

			putitem/id TV_OUTPUT,"success","false"
			putitem/id TV_OUTPUT,"message",TV_MESSAGE
			call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
			#include NTIER:CHECK_ERROR
			$webinfo("output")=TV_OUTPUT
			$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"
			$webinfo("STATUS")=401
			return <GC_STOP>
		endif

		;; Magnus Mackay 28/06/16 #84581 - Handle error status by initialising status boolean flag to false
		TV_SUCCESS  = 0

		newinstance "BSJSON",TV_BSINSTANCE
		activate TV_BSINSTANCE.OP_JSON2LIST2("","",$webinfo("input"),TV_PAYLOAD) ;mmb spr-86399, changed to use structs ie. from OP_JSON2LIST to OP_JSON2LIST2
		#include NTIER:CHECK_ERROR

		; MRB 28/04/26 SPR # 103472
		if (TV_PAYLOAD = "") $status = -10	

	endif
	;SPR 87196 ends

	; MRB 28/04/26 SPR # 103472
	if ($status = -10)
		putitem/id TV_OUTPUT,"success", "false"
		putitem/id TV_OUTPUT,"message", "Empty payload"
		call LP_PROCESS_OUTPUT(TV_OUTPUT, TV_OUTPUT)
		#include NTIER:CHECK_ERROR
		$webinfo("output") = TV_OUTPUT
		$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"
		$webinfo("STATUS") = 403
		return <GC_STOP>
	endif

	if ($status = 0)
		deleteinstance TV_BSINSTANCE ;mmb spr-85806 21-sep-2016 END
		TV_USERNAME= $item("username",TV_PAYLOAD)
		TV_PASSWORD = $item("password",TV_PAYLOAD)
		TV_LANG = $item("language",TV_PAYLOAD)
		TV_CONNECTIONPOOL = $item("connectionpool",TV_PAYLOAD)
		$LV_SESS_ID$ = $webinfo("UserContext")	
		newinstance "GSSESSION", TV_INSTANCE
		#include NTIER:CHECK_ERROR

		;SPR #88999 11/09/2017 GS - Temporary work-around uses SPDEDPORTAL.LOGIN as a pre-flight for SSO. If it has created a session we validate it here and skip the login process and just return the session information instead
		if (($logical("SSO_MODE") != <GC_NULL>) && ($LV_SESS_ID$ != <GC_NULL>) && (TV_USERNAME != <GC_NULL>) && (TV_PASSWORD == <GC_NULL>))
			activate TV_INSTANCE.INIT_SESSION($LV_SESS_MESS$, $LV_SESS_ID$, $result)
			#include NTIER:CHECK_ERROR
			if ($item("USERNAME", $result) == TV_USERNAME)
				TV_SSO_LOGIN = <GC_TRUE>
			endif
		endif

		if (TV_SSO_LOGIN != <GC_TRUE>) ;Carry on as before if this is not SSO
		;SPR 88999 ends

			activate TV_INSTANCE."CREATE_SESSION"($LV_SESS_MESS$,$web,$LV_SESS_ID$) 
			#include NTIER:CHECK_ERROR
	
	 		if ($logical("DEFAULT_LANGUAGE") = "") 
				activate TV_INSTANCE."UPDATE_SESSION"($LV_SESS_MESS$, "LANGUAGE" , "ENG" )  
				#include NTIER:CHECK_ERROR
			else  
				activate TV_INSTANCE."UPDATE_SESSION"($LV_SESS_MESS$, "LANGUAGE" , $uppercase($logical("DEFAULT_LANGUAGE")) )  
				#include NTIER:CHECK_ERROR
			endif 
			;SPR#79485 - Adding MOBILE as second item of user parameter - Luis Buron - 24/02/2015
			;;spr 69745 start, added extra param
			;activate "BSDEMLOGIN"."VALIDATE_PASSWORD"($LV_SESS_MESS$, TV_USERNAME , TV_PASSWORD , TV_CREDENTIALS,<GC_TRUE>) 
			;;spr 69745 end
			;SPR #94994 02/09/2019 GS - New parameters added to VALIDATE_PASSWORD
			;TV_USER = "%%TV_USERNAME%%%[[uSEP]]MOBILE"
			;activate "BSDEMLOGIN"."VALIDATE_PASSWORD"($LV_SESS_MESS$, TV_USER , TV_PASSWORD , TV_CREDENTIALS,<GC_TRUE>)
			; SPR #101460 - 29/11/2023 - This is only called from within the API - Jon Clark
			;activate "BSDEMLOGIN"."VALIDATE_PASSWORD"($LV_SESS_MESS$, TV_USERNAME, TV_PASSWORD, TV_CREDENTIALS, <GC_TRUE>, "MOBILE", "", "")
			activate "BSDEMLOGIN"."VALIDATE_PASSWORD"($LV_SESS_MESS$, TV_USERNAME, TV_PASSWORD, TV_CREDENTIALS, <GC_TRUE>, "API", "", "")
			; SPR #101460 - 29/11/2023 - END
			#include NTIER:CHECK_ERROR
			;SPR 94994 ends
			;SPR 79485 - Luis Buron - 24/02/2015 - END
		endif ;SPR #88999 11/09/2017 GS - Temporary work-around uses SPDEDPORTAL.LOGIN as a pre-flight for SSO. If it has created a session we validate it here and skip the login process and just return the session information instead
		if ($status < 0)
			activate "GSMSG"."GET_MESSAGE"( $LV_SESS_MESS$,TV_ERROR,"E") 
			#include NTIER:CHECK_ERROR
;			TV_ERROR = "SEC0014 : Invalid Username or Password."
			length TV_ERROR
			TV_END = $result
			scan TV_ERROR,":"
			TV_COLON = $result + 2
			TV_ERROR  = TV_ERROR[TV_COLON,TV_END]
			putitem/id TV_OUTPUT,"success","false"
			putitem/id TV_OUTPUT,"message",""
			putitem/id TV_OUTPUT,"error","true"
			putitem/id TV_OUTPUT,"errorText",TV_ERROR
			; SPR #101460 - 05/10/2023 - Jon Clark
			; PLACEHOLDER FOR LOGIN FAILURE
			TV_USERNAME= $item("username",TV_PAYLOAD)
			call LP_AUDIT_LOGIN_FAIL($LV_SESS_MESS$,TV_ULEVEL)
			#include NTIER:CHECK_ERROR
			$webinfo("UserContext") = ""
			; SPR #101460 - 05/10/2023 - END
		else
			; SPR 100178 - Neil Payne - 16/11/22 - use instance instead
			;activate "GSSESSION".GET_SESSION ($LV_SESS_MESS$, "LANGUAGE", TV_LANG)
			activate TV_INSTANCE.GET_SESSION ($LV_SESS_MESS$, "LANGUAGE", TV_LANG)
			;/SPR 100178
			#include NTIER:CHECK_ERROR
 			if (TV_LANG = "")
				activate TV_INSTANCE."UPDATE_SESSION"($LV_SESS_MESS$, "LANGUAGE" , "ENG" )
				#include NTIER:CHECK_ERROR
				deleteinstance TV_INSTANCE	
				TV_LANG = "ENG"
			endif
;spr 67318 start
			TV_LIST = "U_USER=%%TV_USERNAME%%%"
			activate "GSVALIDATE".EXISTS ($LV_SESS_MESS$, "EUSERS", "", TV_LIST)
			#include NTIER:CHECK_ERROR
			if ($status = 0)
				getitem/id TV_USER_EMAIL, TV_LIST, "U_FREE"
				;SPR#79485 - Get User Level - Luis Buron - 24/02/2015
				getitem/id TV_ULEVEL, TV_LIST, "U_LEVEL"
				;SPR 79485 - Luis Buron - 24/02/2015 - END
			endif
;spr 67318 end
			TV_LIST = "UA_USER=%%TV_USERNAME%%%"
			activate "GSVALIDATE".EXISTS ($LV_SESS_MESS$, "EUSERSA", "", TV_LIST)
			#include NTIER:CHECK_ERROR
			if ($status = 0)
			      getitem/id TV_FULL_NAME, TV_LIST, "UA_NAME"
			endif
			; SPR 100178 - Neil payne - 16/11/22 - not needed and causing many errors in the error log
			;newinstance "GSSESSION", TV_INSTANCE
			;#include NTIER:CHECK_ERROR
			;/SPR 100178
			activate TV_INSTANCE.INIT_SESSION($LV_SESS_MESS$, $LV_SESS_ID$, $LV_SESS$)
			#include NTIER:CHECK_ERROR
			deleteinstance TV_INSTANCE

			; MRB 02/03/16 SPR # 82323
;			activate "BSREQPORTAL".GETUSERROLE($LV_SESS_MESS$, TV_USERNAME, TV_ROLE)
			; spr for mobile phase 3
;			activate "BSREQPORTAL".GetContactDetail($LV_SESS_MESS$, TV_PAYLOAD, TV_ERROR, TV_PK,'',TV_CONTACT_DETAIL)
;			#include NTIER:CHECK_ERROR
			if ($item("text/json", $webinfo("input")) != "")
				; This isnt mobile so ignore all the contact/supplier validation
				$status = 0
			else
				activate "BSREQPORTAL".GetContactDetail($LV_SESS_MESS$, TV_PAYLOAD, TV_ERROR, TV_PK,'',TV_CONTACT_DETAIL)
				#include NTIER:CHECK_ERROR
			endif
			; End MRB

			if ($status < 0)
;			activate "BSREQPORTAL".GETLABELLANG($LV_SESS_MESS$, TV_LANG, TV_LABEL_LANG)
;		TV_ROLE = PS_RES_TYPE.PERSONNEL from users to contact to contacta to personnel
				putitem/id TV_OUTPUT,"success","false"
				putitem/id TV_OUTPUT,"error","true"
;spr 73518 start
;				call LP_ERROR(TV_ERROR)
;				#include NTIER:CHECK_ERROR
;spr 73518 end
;spr 73518 start
				putitem/id TV_OUTPUT,"errorId",TV_ERROR
;				putitem/id TV_OUTPUT,"errorText",TV_ERROR
;spr 73518 start
				;SPR#76289 - Display message - Luis Buron - 11/08/2014
				getitem/id TV_ERROR, TV_CONTACT_DETAIL, "errorText"
				putitem/id TV_OUTPUT,"errorText",TV_ERROR
				putitem/id TV_OUTPUT,"message",""
				;SPR 76289 - Display message - Luis Buron - 11/08/2014 - END
				; SPR #101460 - 05/10/2023 - Jon Clark
				TV_USERNAME= $item("username",TV_PAYLOAD)
				call LP_AUDIT_LOGIN_FAIL($LV_SESS_MESS$,TV_ULEVEL)
				#include NTIER:CHECK_ERROR
				$webinfo("UserContext") = ""
				; SPR #101460 - 05/10/2023 - END
			else
				;SPR#79485 - Inform the Audit Trail, user has logged on - Luis Buron - 24/02/2015
				call LP_AUDIT_LOGIN($LV_SESS_MESS$,TV_ULEVEL)
				#include NTIER:CHECK_ERROR
				;SPR 79485 - Luis Buron - 24/02/2015 - END

				getitem/id TV_RLS,TV_CONTACT_DETAIL,"RLS_WHERE"
				getitem/id TV_CONTACT,TV_CONTACT_DETAIL,"CD_CONTACT"
;spr 73518 start
;				TV_ERROR = "SEC0025"
				TV_ERROR = "UI110";Log in successful             
;spr 73518 end
				call LP_ERROR(TV_ERROR)
				#include NTIER:CHECK_ERROR
				putitem/id TV_OUTPUT,"success","true"
				putitem/id TV_OUTPUT,"message",""
				putitem/id TV_OUTPUT,"sessionID",$LV_SESS_ID$
				putitem/id TV_OUTPUT,"language",TV_LANG
				putitem/id TV_OUTPUT,"labellanguage",TV_LABEL_LANG
				putitem/id TV_OUTPUT,"error","false"
;spr 73518 start
				putitem/id TV_OUTPUT,"errorId",TV_ERROR
;				putitem/id TV_OUTPUT,"errorText",TV_ERROR
;spr 73518 start
				putitem/id TV_OUTPUT,"fullName",TV_FULL_NAME
				putitem/id TV_OUTPUT,"role",TV_ROLE
				putitem/id TV_OUTPUT,"contact",TV_CONTACT
				putitem/id TV_OUTPUT,"RLS_WHERE",TV_RLS
;spr 67318 start
				putitem/id TV_OUTPUT,"userEmail",TV_USER_EMAIL
;spr 67318 end
				;SPR #88999 11/09/2017 GS - Temporary work-around uses SPDEDPORTAL.LOGIN as a pre-flight for SSO. If it has created a session we validate it here and skip the login process and just return the session information instead
				;Front-end currently gets the username from the login form before it is submitted. Apparently there is at least one call where it sends this back to the server in DO, so we need to let it know who the user is (if it gets here then the Space code has fired the SSO login and the JavaScript is completely unaware of anything about the user at this point)
				if (TV_SSO_LOGIN == <GC_TRUE>) putitem/id TV_OUTPUT, "username", TV_USERNAME
				;SPR 88999 ends

				;SPR #94093 24/04/2019 GS - Output WOPARTSOPT parameter
				activate "GSPMSYSTEM".OP_GET_PARAM($LV_SESS_MESS$, "WOPARTSOPT", "Y", TV_WOPARTSOPT)
				#include NTIER:CHECK_ERROR
				putitem/id TV_OUTPUT, "params", "WOPARTSOPT=%%TV_WOPARTSOPT"
				;SPR 94093 ends
				;; Magnus Mackay 28/06/16 #84581 - Set status boolean flag to true
				TV_SUCCESS = 1

			endif
		endif
	else
		deleteinstance TV_BSINSTANCE ;mmb spr-85806 21-sep-2016 END
		putitem/id TV_OUTPUT,"success","false"
		putitem/id TV_OUTPUT,"message",""
		putitem/id TV_OUTPUT,"error","true"
;spr 73518 start
		TV_ERROR = "UI111"	;Error encoding                  
		putitem/id TV_OUTPUT,"errorId",TV_ERROR
		putitem/id TV_OUTPUT,"errorText","Error encoding"
;spr 73518 start
		; SPR #101460 - 18/10/2023 - Jon Clark
		call LP_AUDIT_LOGIN_FAIL($LV_SESS_MESS$,TV_ULEVEL)
		#include NTIER:CHECK_ERROR
		$webinfo("UserContext") = ""
		; SPR #101460 - 18/10/2023 - END
	endif
	if (TV_OUTPUT)
		;SPR #94093 24/04/2019 GS - Handle nested output object
		;call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
		TV_OUTPUT = LF_PROCESS_OUTPUT(TV_OUTPUT, <GC_FALSE>)
		#include NTIER:CHECK_ERROR
	endif
	$webinfo("output")=TV_OUTPUT
	$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"

	;; Magnus Mackay 28/06/16 #84581 - Handle error status 
	if (!TV_SUCCESS)
		$webinfo("STATUS")=403
		$webinfo("statusreason")="Forbidden"
	endif
	$webinfo("UserContext") = "" ; SPR #101460 - 15/12/2023 - Jon Clark (do not change the cookie for API login/logout)


end

;mmb spr-86399 not required
;operation INIT
;variables
;  string TV_MESSAGE
;  string TV_LANGUAGE
;  string TV_SESSIONID
;  string TV_LICENSE
;  string TV_TEMP
;  string TV_INSTANCE
;	string TV_CREDENTIALS
;endvariables	
;end ; INIT
;;mmb spr-86399 not required END

; ############################################################################################

public operation   DO
	public web
	variables
		string TV_PAYLOAD,TV_OUTPUT, TV_DATA, TV_OPERATION, TV_OUTPUTMESSAGE,TV_LANG, TV_SPAREINOUT, TV_SPAREOUT
		string TV_ERROR,TV_PK, TV_INSTANCE, TV_BSINSTANCE, TV_JSON
		boolean TV_RESETCOOKIETONULL
		string  TV_MESSAGE, TV_ERRORTEXT
		string  TV_SECMESSAGE
	endvariables

	; SPR #101460 - 08/01/2024 - Jon Clark
	TV_RESETCOOKIETONULL = "F"
	if ( $webinfo("usercontext") == "" ) TV_RESETCOOKIETONULL = "T"
	; SPR #101460 - 08/01/2024 - END
	
	;SPR #87196 16/02/2017 GS - The new parser wasn't tested with the mobile, which was subsequently borken. Now adding a check to restore the old code if it looks like the old parser will work
	;mmb spr-85806 21-sep-2016............
	;orig
	;	call LP_PROCESS_INPUT("F",$webinfo("input"),TV_PAYLOAD)
	;	#include NTIER:CHECK_ERROR
	;	$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)
	;new
	;newinstance "BSJSON",TV_BSINSTANCE
	;activate TV_BSINSTANCE.OP_JSON2LIST2("","",$webinfo("input"),TV_PAYLOAD) ;mmb spr-86399, changed to use structs ie. from OP_JSON2LIST to OP_JSON2LIST2
	;#include NTIER:CHECK_ERROR
	;$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)
	;if ($LV_SESS_ID$="") $LV_SESS_ID$ = $webinfo("UserContext")
	;deleteinstance TV_BSINSTANCE
	;mmb spr-85806 21-sep-2016 END

	if ($scan($webinfo("input"), $tometa(10)) == 0)
		call LP_PROCESS_INPUT("F",$webinfo("input"),TV_PAYLOAD)
		#include NTIER:CHECK_ERROR
		$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)
	else
		newinstance "BSJSON",TV_BSINSTANCE
		activate TV_BSINSTANCE.OP_JSON2LIST2("","",$webinfo("input"),TV_PAYLOAD) ;mmb spr-86399, changed to use structs ie. from OP_JSON2LIST to OP_JSON2LIST2
		#include NTIER:CHECK_ERROR
		$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)
		if ($LV_SESS_ID$="") $LV_SESS_ID$ = $webinfo("UserContext")
		deleteinstance TV_BSINSTANCE
	endif
	;SPR 87196 ends

	$LV_FAILURE$ = <GC_NULL> ; SPR #101460 - 23/11/2023 - Jon Clark

	; 101895 - Neil Payne - 28/03/24 - validate the API KEY and whitelist if set
	activate "BSAPISEC".VALIDATE_SECURITY(TV_SECMESSAGE)
	if ( $status < 0 )
		if ( $status == -1 )
			TV_ERROR  = "UI190" ; Invalid API Key
		elseif ( $status == -2 )
			TV_ERROR  = "UI191" ; Invalid IP Address
		endif
		; SPR #101460 - 20/10/2023 - Jon Clark
		call LP_AUDIT_FAIL(<GC_NULL>, TV_PAYLOAD, TV_SECMESSAGE)
		#include NTIER:CHECK_ERROR
		$webinfo("usercontext") = ""
	else
	;/101895
		if ($LV_SESS_ID$ = "")
			
			; MRB 05/05/16 SPR # 84431
			;delitem/id TV_PAYLOAD, "sessionID"
			;newinstance "GSSESSION", TV_INSTANCE
			;#include NTIER:CHECK_ERROR
			;activate TV_INSTANCE."CREATE_SESSION"($LV_SESS_MESS$,$web,$LV_SESS_ID$)
			;#include NTIER:CHECK_ERROR
			;deleteinstance TV_INSTANCE
			TV_ERROR = "UI112" ;Your session has expired. Please log in again before proceeding

			; SPR #101460 - 20/10/2023 - Jon Clark
			call LP_AUDIT_FAIL(<GC_NULL>, TV_PAYLOAD, "Your session has expired. Please log in again before proceeding")
			; SPR #101460 - 20/10/2023 - END
		else
			newinstance "GSSESSION", TV_INSTANCE
			#include NTIER:CHECK_ERROR
			activate "GSSESSION"."INIT_SESSION"($LV_SESS_MESS$ , $LV_SESS_ID$ , $LV_SESS$ )
			#include NTIER:CHECK_ERROR
			if ($status = 0) 
				TV_OPERATION = $item("method",TV_PAYLOAD)
				TV_DATA = $item("fields",TV_PAYLOAD)
				TV_LANG = $item("language",TV_PAYLOAD)
				if (TV_LANG = "")
	;spr 73518 start
					activate "GSSESSION".GET_SESSION ($LV_SESS_MESS$, "LANGUAGE", TV_LANG)
					if (TV_LANG = "")
	;spr 73518 end
						activate TV_INSTANCE."UPDATE_SESSION"($LV_SESS_MESS$, "LANGUAGE" , "ENG" )
						#include NTIER:CHECK_ERROR
						deleteinstance TV_INSTANCE	
						TV_LANG = "ENG"
					endif
				endif
	;Denis OBS service
				if (TV_OPERATION="manageSpaceOBS")
					activate "BSOBSPORTAL"."%%TV_OPERATION%%%"($LV_SESS_MESS$,TV_DATA,TV_ERROR,TV_PK,TV_SPAREINOUT,TV_OUTPUT)
					#include NTIER:CHECK_ERROR
					; SPR #101460 - 20/10/2023 - Jon Clark
					call LP_AUDIT_SUCCESS($LV_SESS_MESS$, TV_PAYLOAD, "Successful call to %%TV_OPERATION%%%", TV_OPERATION)
					; SPR #101460 - 20/10/2023 - END
				elseif (TV_OPERATION[1:4]="CLOG") ;mmb spr 82697 8-jan-2016 (code re-inserted)
					activate "BSCLOGPORTAL"."%%TV_OPERATION%%%"($LV_SESS_MESS$,TV_DATA,TV_ERROR,TV_PK,TV_SPAREINOUT,TV_OUTPUT)
					#include NTIER:CHECK_ERROR
					; SPR #101460 - 20/10/2023 - Jon Clark
					call LP_AUDIT_SUCCESS($LV_SESS_MESS$, TV_PAYLOAD, "Successful call to %%TV_OPERATION%%%", TV_OPERATION)
					; SPR #101460 - 20/10/2023 - END
					;mmb spr 82697 2-jan-2016 -- tv_output is already returned as multi-level json - so conversion is only required once.
					$webinfo("output")=TV_OUTPUT
					$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"

					; SPR #101460 - 08/01/2024 - Jon Clark
					if ( TV_RESETCOOKIETONULL == "T" )
						$webinfo("usercontext") = ""
					endif
					; SPR #101460 - 08/01/2024 - END

					return 0
				else
					activate "BSREQPORTAL"."%%TV_OPERATION%%%"($LV_SESS_MESS$,TV_DATA,TV_ERROR,TV_PK,TV_SPAREINOUT,TV_OUTPUT)
					#include NTIER:CHECK_ERROR
				endif
				if ($status < -1)
					TV_OUTPUT="status=-1[[uSEP]]message=Unknown method"
					; SPR #101460 - 11/12/2023 - Jon Clark
					call LP_AUDIT_FAIL($LV_SESS_MESS$, TV_PAYLOAD, $concat(TV_PAYLOAD, "%%^", "Unknown method"))
					#include NTIER:CHECK_ERROR
					; SPR #101460 - 11/12/2023 - END

				elseif($status = -1)
					putitem/id TV_OUTPUT,"error","true"
					; SPR #101460 - 08/01/2024 - Jon Clark
					;api returned an error
					call LP_AUDIT_FAIL($LV_SESS_MESS$, TV_PAYLOAD, $concat(TV_PAYLOAD, "%%^", "API returned an error"))
					#include NTIER:CHECK_ERROR
					; SPR #101460 - 08/01/2024 - END
				endif
			else
	;spr 73518 start
	;			TV_ERROR = "Error with Session ID"
				TV_ERROR  = "UI112"
				; SPR #101460 - 20/10/2023 - Jon Clark
				call LP_AUDIT_FAIL($LV_SESS_MESS$, TV_PAYLOAD, "Error with Session ID")
				#include NTIER:CHECK_ERROR
				$webinfo("usercontext") = ""
				; SPR #101460 - 20/10/2023 - END
	;spr 73518 start
			endif
		endif
	endif
	if (TV_ERROR)
;spr 73518 start
;		call LP_ERROR(TV_ERROR)
;		#include NTIER:CHECK_ERROR
;spr 73518 end
;spr 73518 start
;		putitem/id TV_OUTPUT,"errorText",TV_ERROR
		putitem/id TV_OUTPUT,"errorId",TV_ERROR

		; SPR 101895 - Neil Payne - 28/03/24 - get the message from manmess 
		if ( TV_LANG == "" ) TV_LANG = "ENG"
		clear/e "MANMESS"
		ID.MANMESS = TV_ERROR
		LANGUAGE.MANMESS = TV_LANG
		retrieve/e "MANMESS"
		if ( $status = 0 ) TV_ERRORTEXT = MESSAGE.MANMESS
		if ( TV_ERROR == "UI190" || TV_ERROR == "UI191" )
			putitem/id TV_OUTPUT,"errorText",TV_SECMESSAGE
		else
			putitem/id TV_OUTPUT,"errorText",TV_ERRORTEXT
		endif
		clear/e "MANMESS"
		;/SPR 101895

		; MRB 05/05/16 SPR # 84431
		if (TV_ERROR  == "UI112") putitem/id TV_OUTPUT, "error", "true"

;spr 73518 end
	endif
	;SPR #69113 15/05/2013 GS - Need to handle multiple occurences in a list
	if (TV_OPERATION="GetDocuments")
		;SPR #71530 22/10/2013 GS - Correct number of arguments
;		call LP_PROCESS_MULTIPLE_OUTPUT(TV_OUTPUT,TV_OUTPUT)
		call LP_PROCESS_MULTIPLE_OUTPUT(TV_OUTPUT,<GC_FALSE>,TV_OUTPUT)
	; SPR #101460 - 20/10/2023 - Jon Clark
		call LP_AUDIT_SUCCESS($LV_SESS_MESS$, TV_PAYLOAD, "Successful call to GetDocuments", TV_OPERATION)
	elseif ($scan(TV_OUTPUT, "status=-1") > 0)
		call LP_AUDIT_FAIL($LV_SESS_MESS$, TV_PAYLOAD, "Unknown method", TV_OPERATION)
	; SPR #101460 - 20/10/2023 - END
	else ;SPR 69113 ends
		call LP_PROCESS_OUTPUT(TV_OUTPUT,TV_OUTPUT)
		; SPR #101460 - 20/10/2023 - Jon Clark
		if ($LV_FAILURE$ != <GC_FALSE>) call LP_AUDIT_SUCCESS($LV_SESS_MESS$, TV_PAYLOAD, "Successful call to %%TV_OPERATION%%%", TV_OPERATION)
		; SPR #101460 - 20/10/2023 - END
	endif
	#include NTIER:CHECK_ERROR
	$webinfo("output")=TV_OUTPUT
	$webinfo("HTTPRESPONSEHEADERS") = "Content-Type=text/json;charset=utf-8"

	; SPR #101460 - 08/01/2024 - Jon Clark
	if ( TV_RESETCOOKIETONULL == "T" )
		$webinfo("usercontext") = ""
	endif
	; SPR #101460 - 08/01/2024 - END
end

;##########################################################################################################################
;SPR #70121/70663 28/08/2013 GS - Survey Portal
public operation SURVEY_PORTAL
	public web
	variables
		string  TV_GUID, TV_SURVEYDETAILS, TV_METHOD, TV_TEMP
	endvariables
	
	TV_GUID = $item("GUID",$webinfo("INPUT"))
	TV_METHOD = $item("Method",$webinfo("INPUT"))
	selectcase (TV_METHOD)
		case "getLanguage"
			activate "BSREQPORTAL".GetSurveyLanguage ("",$item("Language",$webinfo("INPUT")),TV_SURVEYDETAILS)
			call LP_PROCESS_MULTIPLE_OUTPUT (TV_SURVEYDETAILS,<GC_TRUE>,TV_SURVEYDETAILS)
			$webinfo("OUTPUT") = TV_SURVEYDETAILS
		case "getSurvey" ;fetch questions
			if (TV_GUID == <GC_NULL>) exit (<GC_STOP>)
			activate "BSREQPORTAL".GetSurveyDetails ("",TV_GUID,TV_SURVEYDETAILS)
			call LP_PROCESS_MULTIPLE_OUTPUT (TV_SURVEYDETAILS,<GC_TRUE>,TV_SURVEYDETAILS)
			$webinfo("OUTPUT") = TV_SURVEYDETAILS
		elsecase ;submit response
			TV_SURVEYDETAILS = $item("data",$webinfo("INPUT"))
			call LP_JSON2LIST('',TV_SURVEYDETAILS,TV_SURVEYDETAILS)
			TV_GUID = $item("GUID",TV_SURVEYDETAILS)
			TV_TEMP = TV_SURVEYDETAILS[($scan(TV_SURVEYDETAILS,"questions=0=") + 12)]
			TV_TEMP = $replace(TV_TEMP,1,"{","",-1)
			TV_TEMP = $replace(TV_TEMP,1,"}","",-1)
			TV_TEMP = $replace(TV_TEMP,1,"[[uNOT]]","",-1)
			TV_TEMP = $replace(TV_TEMP,1,"[[uSEP]]","[[uNOT]][[uSEP]]",-1)
			TV_TEMP = $replace(TV_TEMP,1,"=id=","=[[uSEP]]id=",-1)
			TV_SURVEYDETAILS = $concat("ResponseComments=",$item("ResponseComments",TV_SURVEYDETAILS))
			putitem/id TV_SURVEYDETAILS, "questions", TV_TEMP
			activate "BSREQPORTAL".CreateSurveyResponse ("",TV_GUID,TV_SURVEYDETAILS)
	endselectcase
	return (<GC_OK>)
end

public operation UPLOAD
	public web
;SPR 71680 (replicating SPR 69113 by GS) - Document upload - 07/11/2013 - LBB
	variables
		string  TV_PAYLOAD
		string  TV_INSTANCE
		string  TV_DATA
		string  TV_LANG
		string  TV_OUTPUT, TV_OPERATION, TV_OUTPUTMESSAGE, TV_SPAREINOUT, TV_SPAREOUT,TV_ERROR,TV_PK
		raw     TV_RAW
		numeric TV_DD_ID, TV_DD_VERSION, TV_FILESIZE ;SPR #88422 19/07/2017 GS - Handle updates to existing documents
		string  TV_FILENAME, TV_EXTRA_OUT ;SPR #88422 19/07/2017 GS - Handle updates to existing documents
		struct  TV_RESPONSE ;SPR #88422 19/07/2017 GS - Provide a meaningful response
	endvariables
	putitem/id TV_DATA, "DATA", $item("JSON.FILE.DUMMY", $webinfo("INPUT")) 
	call LP_PROCESS_INPUT("F",TV_DATA,TV_PAYLOAD)
	;SPR #88422 19/07/2017 GS - Check to see if we are updating an exisitng document
	getitem/id/case TV_DD_ID, $item("fields",TV_PAYLOAD), "docPK"
	getitem/id/case TV_DD_VERSION, $item("fields",TV_PAYLOAD), "docVersion"
	getitem/id/case TV_FILENAME, $item("fields",TV_PAYLOAD), "docFilename"
	if ($status == 0) TV_DD_VERSION = ;Default it to 0 rather than null to force the CHECK_IN to validate the version number
	;SPR 88422 ends
	fileload/web "CONTENT.FILE.DUMMY", TV_RAW
	TV_FILESIZE = $status ;SPR #88422 19/07/2017 GS - Get the filesize here as it is more efficient than calculating it later
	$LV_SESS_ID$ = $item("sessionID",TV_PAYLOAD)

	if ($LV_SESS_ID$ = "")
		delitem/id TV_PAYLOAD, "sessionID"
		newinstance "GSSESSION", TV_INSTANCE
		#include NTIER:CHECK_ERROR
		activate TV_INSTANCE."CREATE_SESSION"($LV_SESS_MESS$,$web,$LV_SESS_ID$)
		#include NTIER:CHECK_ERROR
		deleteinstance TV_INSTANCE
	else
		newinstance "GSSESSION", TV_INSTANCE
		activate "GSSESSION"."INIT_SESSION"($LV_SESS_MESS$ , $LV_SESS_ID$ , $LV_SESS$ )
		if ($status = 0) 
			TV_OPERATION = $item("method",TV_PAYLOAD)
			TV_DATA = $item("fields",TV_PAYLOAD)
			TV_LANG = $item("language",TV_PAYLOAD)
			if (TV_LANG = "")
				activate TV_INSTANCE."UPDATE_SESSION"($LV_SESS_MESS$, "LANGUAGE" , "ENG" )
				deleteinstance TV_INSTANCE	
				TV_LANG = "ENG"
			endif
			;SPR #88422 19/07/2017 GS - Check-in a new version of an existing document
			if (TV_DD_ID > 0)
				TV_RESPONSE = $newstruct
				;activate "BSDBMDOCMGT".CHECK_IN($LV_SESS_MESS$, TV_DD_ID, "", "", "", "", TV_FILENAME, TV_FILESIZE, TV_RAW, "DD_VERSION=%%TV_DD_VERSION%%%[[uSEP]]COMMIT=T", TV_EXTRA_OUT)
				activate "BSFMPORTAL".CheckInDocument($LV_SESS_MESS$, TV_DD_ID, TV_DD_VERSION, TV_FILENAME, TV_FILESIZE, TV_RAW, "", TV_EXTRA_OUT)
				#include NTIER:CHECK_ERROR
				if ($status < 0)
					;Handle error response
					activate "GSMSG".GET_MESSAGE($LV_SESS_MESS$, TV_OUTPUTMESSAGE, "")
					#include NTIER:CHECK_ERROR
					if (TV_OUTPUTMESSAGE == <GC_NULL>) ;Service did not update PV_MESSAGE (e.g. activate error) so we create our own catch-all message
						TV_ERROR = "DM0021" ;File check-in failed
						activate "GSMSG".MAKE_MESSAGE($LV_SESS_MESS$, TV_ERROR, "", TV_OUTPUTMESSAGE)
						#include NTIER:CHECK_ERROR
					else ;Use the message returned from the server
						$result = $split(TV_OUTPUTMESSAGE, 1, " : ", TV_ERROR, TV_OUTPUTMESSAGE)
					endif
					TV_RESPONSE->error = "true"
				else
					TV_ERROR = "DM0002" ;Document checked in
					activate "GSMSG".MAKE_MESSAGE($LV_SESS_MESS$, TV_ERROR, "", TV_OUTPUTMESSAGE)
					#include NTIER:CHECK_ERROR
					TV_RESPONSE->error = "false"
					;Rebuild the document object (so the front-end doesn't need to fetch the whole list again)
					TV_RESPONSE->docPK = $item("DD_ID", TV_EXTRA_OUT)
					TV_RESPONSE->docVersion = $item("DD_VERSION", TV_EXTRA_OUT)
					TV_RESPONSE->docTable = $item("DD_TABLE", TV_EXTRA_OUT)
					TV_RESPONSE->docFolder = $item("DD_BINDER", TV_EXTRA_OUT)
					TV_RESPONSE->docFK = $item("DD_FK", TV_EXTRA_OUT)
					if ($item("DD_TITLE", TV_EXTRA_OUT) == <GC_NULL>)
						TV_RESPONSE->docTitle = $item("DD_FILENAME", TV_EXTRA_OUT)
					else
						TV_RESPONSE->docTitle = $item("DD_TITLE", TV_EXTRA_OUT)
					endif
					TV_RESPONSE->docDesc = $item("DD_DESC", TV_EXTRA_OUT)
					TV_RESPONSE->docFilename = $item("DD_FILENAME", TV_EXTRA_OUT)
					TV_RESPONSE->docType = $item("DD_TYPE", TV_EXTRA_OUT)
					TV_RESPONSE->docModDate = $item("DD_UPDATED", TV_EXTRA_OUT)
					TV_RESPONSE->docModUser = $item("DD_UPDATEU", TV_EXTRA_OUT)
					TV_RESPONSE->docURL = $item("docURL", TV_EXTRA_OUT)
					TV_RESPONSE->docUpdateable = $item("docUpdateable", TV_EXTRA_OUT)
				endif
				TV_RESPONSE->errorID = TV_ERROR
				TV_RESPONSE->errorText = TV_OUTPUTMESSAGE
				structToJson $webinfo("OUTPUT"), TV_RESPONSE
				putitem/id $webinfo("HTTPRESPONSEHEADERS"), "Content-Type", "text/json"
				return (<GC_OK>)
			endif
			;SPR 88422 ends
			activate "BSDBMDOCMGT"."MOBILE_UPLOAD"($LV_SESS_MESS$,TV_DATA,TV_RAW,TV_ERROR,TV_PK,TV_SPAREINOUT,TV_OUTPUT)
			#include NTIER:CHECK_ERROR
; SPR 102044 - Nikhil Chandran - 03/06/2024 - Replacing old error handling with modern JSON - START
;			if ($status < -1)
;				rollback
;				TV_OUTPUT="status=-1·;message=Unknown method"
;			elseif($status = -1)
;				rollback
;				putitem/id TV_OUTPUT,"error","true"
;			else
;				commit ;SPR #88422 21/07/2017 GS - Add error handling to commit and fire alerts
;				#include NTIER:CHECK_ERROR
;				if ($status < 0)
;					rollback
;					putitem/id TV_OUTPUT,"error","true"
;				elseif ($item("DD_ID", TV_OUTPUT) != <GC_NULL>)
;					activate/async/stateless "ASV_DMDOCALERT".RAISE_ALERT($LV_SESS_MESS$, $item("DD_ID", TV_OUTPUT))
;					#include NTIER:CHECK_ERROR
;				endif
;				;SPR 88422 ends
;			endif
			if ($status <= -1)
				if($status = -1)
					activate "GSMSG".GET_MESSAGE($LV_SESS_MESS$, TV_OUTPUTMESSAGE, "")
					#include NTIER:CHECK_ERROR
					if (TV_OUTPUTMESSAGE == <GC_NULL>) ;Service did not update PV_MESSAGE (e.g. activate error) so we create our own catch-all message
						TV_ERROR = "DM0021" ;File check-in failed
						activate "GSMSG".MAKE_MESSAGE($LV_SESS_MESS$, TV_ERROR, "", TV_OUTPUTMESSAGE)
						#include NTIER:CHECK_ERROR
					else ;Use the message returned from the server
						$result = $split(TV_OUTPUTMESSAGE, 1, " : ", TV_ERROR, TV_OUTPUTMESSAGE)
					endif
				else
					TV_ERROR = "-1"
					TV_OUTPUTMESSAGE = "Unknown method"
				endif
				rollback
				TV_RESPONSE = $newstruct
				TV_RESPONSE->error = "true"
				TV_RESPONSE->errorID = TV_ERROR
				TV_RESPONSE->errorText = TV_OUTPUTMESSAGE
				structToJson $webinfo("OUTPUT"), TV_RESPONSE
				putitem/id $webinfo("HTTPRESPONSEHEADERS"), "Content-Type", "text/json"
			else
				commit ;SPR #88422 21/07/2017 GS - Add error handling to commit and fire alerts
				#include NTIER:CHECK_ERROR
				if ($status < 0)
					rollback
					TV_RESPONSE = $newstruct
					TV_RESPONSE->error = "true"
					TV_RESPONSE->errorID = "-1"
					TV_RESPONSE->errorText = "Commit Failure"
					structToJson $webinfo("OUTPUT"), TV_RESPONSE
					putitem/id $webinfo("HTTPRESPONSEHEADERS"), "Content-Type", "text/json"
				elseif ($item("DD_ID", TV_OUTPUT) != <GC_NULL>)
					activate/async/stateless "ASV_DMDOCALERT".RAISE_ALERT($LV_SESS_MESS$, $item("DD_ID", TV_OUTPUT))
					#include NTIER:CHECK_ERROR
				endif
			endif
; SPR 102044 - Nikhil Chandran - 03/06/2024 - END
		else
			TV_ERROR = "Error with Session ID"
		endif
	endif

end; UPLOAD

;SPR #88999 12/09/2017 GS - Temporary work-around by calling the Portal SSO implementation
public operation SSO_LOGIN
	public web
	variables
		struct  TV_OUTPUT
		numeric TV_STATUS
		string  TV_USERNAME, TV_SESSIONID
	endvariables
	activate "SPDEDPORTAL".LOGIN() ;Will set $webinfo("OUTPUT") with the Portal response object, we only use this if authentication fails 
	#include NTIER:CHECK_ERROR
	jsonToStruct TV_OUTPUT, $webinfo("OUTPUT")
	TV_STATUS = TV_OUTPUT->STATUS->$scalar
	if (TV_STATUS == 0) ;SSO login successful and session created, now provide the Mobile login response
		TV_USERNAME = TV_OUTPUT->USERNAME->$scalar
		TV_SESSIONID = $itemnr(1, $webinfo("UserContext"))
		if (TV_USERNAME != <GC_NULL>)
			;Mimic what the front-end would have sent us if the user was logging in (using a null password and a valid session for that user to supress the password validation)
			$webinfo("INPUT") = $concat("{%%"method%%":%%"login%%",%%"username%%":%%"", TV_USERNAME, "%%",%%"password%%":%%"%%"}=")
			$instancehandle->LOGIN() ;This will set $webinfo("OUTPUT") with the success/failure response from the mobile login process
			#include NTIER:CHECK_ERROR
		endif
		if (($webinfo("STATUS") == 403) || ($status < 0) || TV_USERNAME == <GC_NULL>) ;Mobile login failed
			;Destroy session created by the Portal SSO login process as the user account cannot be used for login
			;Login just fired an async clean-up less that a second ago, so I am call LOGOUT_BATCH_SESSION to supress calling it again
			activate "BSDEMLOGIN".LOGOUT_BATCH_SESSION(TV_SESSIONID, "", "")
			#include NTIER:CHECK_ERROR
			jsonToStruct TV_OUTPUT, $webinfo("OUTPUT")
			TV_OUTPUT->STATUS = -2
			structToJSON $webinfo("OUTPUT"), TV_OUTPUT
		endif
	endif
	
	return (<GC_OK>)
end ;SSO_LOGIN

; SPR 101895 - Nikhil Chandran - 27/03/2024 - START
public operation GET_API_SECINFO
	public web
	variables
		struct  TV_JSON
		numeric TV_STATUS
		string  TV_ENABLE
		struct	TV_STRUCT
	endvariables

	TV_ENABLE = "false"
	clear/e "APISECURITY"
	AS_KEY.APISECURITY = "K"
	retrieve/e "APISECURITY"
	if($status = <GC_OK>)
		setocc "APISECURITY", 1
		if(AS_ENABLE_KEY == "T")
			TV_ENABLE = "true"
		endif
	endif
	clear/e "APISECURITY"

	TV_STRUCT->"securityInformation"=$newstruct
	TV_STRUCT->"securityInformation"->$tags->jsonClass= "object"
	TV_STRUCT->"securityInformation"->"check_api_key"=TV_ENABLE
	;structToJson/whitespace TV_JSON, TV_STRUCT
	structToJSON $webinfo("OUTPUT"), TV_STRUCT
	
end ; GET_API_SECINFO
; SPR 101895 - Nikhil Chandran - 27/03/2024 - END
 
#enddefine
